### PR TITLE
Feat/mobile shadow effect

### LINKED ISSUE #551: A shadow effect for mobile
Our mobile version, for example http://localhost:3000/trees/186737
When we scroll down, the layer of the header and the scrollable area is a bit confusing, we need a shadow effect like the google map, check the video below:
image

https://dadior.s3.ap-northeast-1.amazonaws.com/Screen%20Recording%202022-05-06%20at%2010.58.41%20AM.mp4

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

### PR DESCRIPTION
**Pull request by khalatevarun**
# Description

[comment]: # 'Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.'

Fixes #551 

Added shadow effect to drawer header for a better user experience.

## Type of change

[comment]: # 'Please delete options that are not relevant.'

- [x] New feature (non-breaking change which adds functionality)

## Screenshots

[comment]: # 'Please include screenshots of your changes if relevant.'

|       Before        |       After        |
| :-----------------: | :----------------: |
| 167059476-ef1c2842-3a5e-4634-8422-fd8b346189a6
 |SCR-20220928-14z|

# How Has This Been Tested?

- [ ] Cypress integration
- [ ] Cypress component tests
- [ ] Jest unit tests

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by khalatevarun** [comment]
@RubenSmn could you please review this PR.

**Comment by khalatevarun** [comment]
@RubenSmn could you please review this PR.

**Comment by RubenSmn** [comment]
@khalatevarun as you can see in the video in the issue, we would like to have this shadow visible only when you're not at the top. 

We are also having the issue of the shadow not sitting on top of the Cards and Images as you can see in the screenshot below:

localhost_3000_planters_5449_bounds=9 228515625000002,-34 45221847282655,40 86914062500001,21 453068633086783(Samsung Galaxy S8+)

**Comment by RubenSmn** [comment]
We already have some scroll handlers in place for the content section https://github.com/Greenstand/treetracker-web-map-client/blob/beta/src/components/Drawer.js#L153-L159

**Comment by khalatevarun** [comment]
can you have a look at once again? @RubenSmn @dadiorchen

**Comment by RubenSmn** [comment]
This works awesome with the overlap on the cards and images, super! But there is another issue, like you can see in the screenshot below, the boxshadow is visible all the time. We don't want to show it when the scroll of the content is all the way at the top. Like mentioned in my previous comment the scroll handlers are already in place [here](https://github.com/Greenstand/treetracker-web-map-client/blob/beta/src/components/Drawer.js#L153-L159), the only thing to do is set the shadow when the content is not at the top.

**Comment by khalatevarun** [comment]
Hey @RubenSmn,
I understood what you are trying to say but can I know why do we want to hide when it is on top?
Since the title is anyway sticky we will have to add some shadow to differentiate it from the drawer content even when it is at the top.

**Comment by RubenSmn** [comment]
We want to hide it at the top to create a better user experience. If the user is at the top of the content we want to give the impression that the `title` and the `content` are one with each other (one component). I hope this makes sense to you, the issue itself contains a video with the desired end result.

**Pull request closed without merging**
