### PR TITLE
fix: refine planter image #463

### PR DESCRIPTION
**Pull request by jwgatt**
Fix for previous pull request https://github.com/Greenstand/treetracker-web-map-client/pull/463

Fixes # (463)

Style upgrade

image

### CODE REVIEW

**Comment by jwgatt** [comment]
Any ideas why the CustomShareIcon.cy.js is failing the component test? I haven't modified it and the fork is up to date.

**Comment by dadiorchen** [comment]
Sorry, I guess it's my fault, but didn't get chance to fix it, you can ignore it

**Comment by jwgatt** [comment]
@dadiorchen so we can merge this PR?

**Comment by dadiorchen** [comment]
Thanks, @jwgatt !

**Comment by jwgatt** [comment]
No problem :+1:

**Pull request merged**
