### PR TITLE
feat: admin can now set initial map view

### LINKED ISSUE #1122: Add map and display coordinate information on dashboard
# Description
Some information about this issue: for the Customizable Web Map need to change the start/initial location for the `/` and `/top` pages.

On the Map Settings tab on the dashboard, which can be found at http://localhost:3000/admin/global, we want to have the actual map on the page.

Things needed:
- map to move/zoom to get to the wanted start location
- display the lat, lon, zoom level

Since I am not an expert on UI design, here is a mock to guide you in the right way

map-settings-v0

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

### PR DESCRIPTION
**Pull request by Mohmn**
# Description

[comment]: # 'Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.'

Fixes #1122

## Type of change

[comment]: # 'Please delete options that are not relevant.'

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Screenshots

[comment]: # 'Please include screenshots of your changes if relevant.'

screenshot
image

# How Has This Been Tested?

- [ ] Cypress integration
- [ ] Cypress component tests
- [ ] Jest unit tests

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by RubenSmn — COMMENTED** [review]
This looks great, you already solved #1123! The initial idea is to have the functionality work in reverse order. When the user navigates the map the coordinates and zoom level will update accordingly. Could you add this functionality?

**Comment by Mohmn** [comment]
> This looks great, you already solved #1123! The initial idea is to have the functionality work in reverse order. When the user navigates the map the coordinates and zoom level will update accordingly. Could you add this functionality?

done 
image

**Comment by dadiorchen** [comment]
THis is beautiful

**Comment by Mohmn** [comment]
> When checking out this PR on my machine and running it locally it get a 500 error saying it has something to do with the Web Map Core `Server Error ReferenceError: self is not defined`. I remember this had something to do with needing to import the map dynamicly. But we're doing that.
> 
> I did a clean npm install and it did not help. Any clue?

I also faced the same problem,
But npm i solved it for me
I will look into it and post the updates here

**Comment by Mohmn** [comment]
@RubenSmn  i think i have fixed the problem , can u test it on ur local

**Review by RubenSmn — APPROVED** [review]
Awesome job!

**Comment by Mohmn** [comment]
@RubenSmn  i will give it a go

**Pull request merged**
