### PR TITLE
fix(drawer): unmount runtime error

### LINKED ISSUE #581: Getting Unhandled Runtime Error on /top page
Getting an unhandled runtime error when trying to hit endpoint http://localhost:3000/top.
 
The error dialog closes when we click outside the dialog

Please find screenshot below for more details

image

After clicking outside the error dialog, the dialog minimizes in bottom left corner ('1 error' in red)

image

### PR DESCRIPTION
**Pull request by RubenSmn**
# Description
Add check to see if component reference exists.

[comment]: # 'Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.'

Fixes #581

## Type of change

[comment]: # 'Please delete options that are not relevant.'

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- [ ] Cypress integration
- [ ] Cypress component tests
- [ ] Jest unit tests

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by dadiorchen** [comment]
Hey, that's cool, thanks @RubenSmn !

**Comment by dadiorchen** [comment]
Are you joined in our slack community? If you want please give me you email

**Comment by dadiorchen** [comment]
I can invite you :)

**Comment by RubenSmn** [comment]
@dadiorchen I would like to join! My email is: saaman.ruben@gmail.com

**Pull request merged**
