### PR TITLE
#resolves #151

### LINKED ISSUE #151: Should show the map view correctly
Now the home page didn't show the map view correctly, check screenshot below: 

Actually, the leaflet map view is bigger than what we are seeing, cuz we can not see the zoom control panel, which I guess is out of the browser window.

image

---
Some hints:
* Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
* Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
* To know more about our organization, visit our [website](https://greenstand.org).

### PR DESCRIPTION
**Pull request by danp2392**
I have fixed the issue with the container height for the map for issue resolves #151 
map container width set to 50%
image

### CODE REVIEW

**Comment by dadiorchen** [comment]
@danp2392 I'm so glad to see your first PR, that's great, just one thing: please resolve the conflicts on this PR?

**Comment by dadiorchen** [comment]
@danp2392 please merge the newest code from web-map-site branch, and resolve those conflicts.

**Comment by danp2392** [comment]
Hi, I have resolved the conflicts

**Comment by dadiorchen** [comment]
@danp2392 thanks!

**Pull request merged**
