### PR TITLE
Feat: scroll to top on visiting a new page on mobile

### LINKED ISSUE #1011: Navigating to another page does not place you at the top of that page
# Description
When navigating to another page you do not start at the top of the new page, see the video below for a visual explanation.

[Kooha-2022-09-25-12:22:38.webm](https://user-images.githubusercontent.com/31519867/192138932-c846b449-29af-4d94-8984-882d7fe05b5b.webm)

## To reproduce
- visit: http://localhost:3000/planters/940
- scroll down to the tree section and click a tree

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- For design guidelines checkout our [Figma design](https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap).
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

### PR DESCRIPTION
**Pull request by khalatevarun**
# Description

[comment]: # 'Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.'

Fixes #1011 

## Type of change

[comment]: # 'Please delete options that are not relevant.'

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Screenshots

[comment]: # 'Please include screenshots of your changes if relevant.'

|       Before        |       After        |
| :-----------------: | :----------------: |
|[192138932-c846b449-29af-4d94-8984-882d7fe05b5b (1).webm](https://user-images.githubusercontent.com/68511458/194052667-26c1434b-3f07-41cf-b51d-7fc383c34c83.webm)|https://user-images.githubusercontent.com/68511458/194052472-83e8a9a3-4eb9-4891-a39a-62fb8e0fd427.mp4|

# How Has This Been Tested?

- [ ] Cypress integration
- [ ] Cypress component tests
- [ ] Jest unit tests

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by khalatevarun** [comment]
@RubenSmn @dadiorchen can we add this in a uitility/helper file which can be imported in all pages where we have drawer for mobile, if yes where exactly do I add this?

**Comment by dadiorchen** [comment]
@khalatevarun good job!
I think you can extract it to a function, and put it into the models folder.

But the way, I have two suggestion:

1. the Desktop also has this problem, so please also make sure it work on desktop, not just `isMobile`
2. I think the: wallet and token page also need this.

**Comment by khalatevarun** [comment]
> @khalatevarun good job! I think you can extract it to a function, and put it into the models folder.
> 
> But the way, I have two suggestion:
> 
> 1. the Desktop also has this problem, so please also make sure it work on desktop, not just `isMobile`
> 2. I think the: wallet and token page also need this.

sure will do it

**Comment by khalatevarun** [comment]
@dadiorchen thanks.
Will update changes

**Comment by dadiorchen** [comment]
@khalatevarun can you also add this to wallet and token page?

**Comment by dadiorchen** [comment]
[walletid].js. and [tokenid].js

**Comment by dadiorchen** [comment]
[walletid].js and [tokenid].js page, @khalatevarun what do you think?

**Comment by RubenSmn** [comment]
@dadiorchen If we add this code to the `Layout` components all the pages will automatically have this functionality

**Comment by dadiorchen** [comment]
@RubenSmn I agree, this is also a good solution

**Comment by dadiorchen** [comment]
@khalatevarun can you check the integration test in the CI above?

**Pull request closed without merging**
