### PR TITLE
Organizations time element 

### PR DESCRIPTION
**Pull request by Harshalyadav**
# Description

 Added Time element in the Organization page for mobile view.

### CODE REVIEW

**Review by RubenSmn — CHANGES_REQUESTED** [review]
Could you remove the changes for the wallet page since this is a PR for the organizations. The wallet time elements have been fixed by #1524

**Comment by Harshalyadav** [comment]
I reverted this feat: add time elements in wallet page can you check again

**Comment by RubenSmn** [comment]
Changes are not visible on the PR, did you forget to push @Harshalyadav ?

**Comment by RubenSmn** [comment]
Fixed by #1526

**Pull request closed without merging**
