### PR TITLE
fix: added feedback to zoom in/out and max buttons

### LINKED ISSUE #528: A image-based button similar as Fab in mui
We need a button with image behavior like Fab component in mui, or we can use Fab directly by setting up correctly.

When mouse hoving over the icon, we need some highlight to give user some feedback.

https://dadior.s3.ap-northeast-1.amazonaws.com/Screen%20Recording%202022-04-25%20at%2011.50.52%20AM.mp4

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

### PR DESCRIPTION
**Pull request by kenleyshaw**
# Button similar to MUI Fab when navigating on the map

[comment]: # 'Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.'

Fixes #528 
Added MUI Fab component and MUI icons to the existing buttons that operate as map navigation. When hovered, the buttons show feedback by changing colors.

## Type of change

[comment]: # 'Please delete options that are not relevant.'

- [x] Bug fix (non-breaking change which fixes an issue)

## Screenshots

[comment]: # 'Please include screenshots of your changes if relevant.'
Screen Shot 2022-04-26 at 5 32 09 PM

# How Has This Been Tested?

- [ ] Cypress integration
- [ ] Cypress component tests
- [ ] Jest unit tests

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by dadiorchen** [comment]
@kenleyshaw It might be my fault that I didnt' make a clear case for this issue , take a look this design, we need to respect the UI here, AND make it a button, actually I have downloaded the image from Figma, so what we need is to solve the feedback stuff (highlight, feedback on clicking). I saw your code you are using Fab, that's good, so the question is if we can use the Fab and implement the UI as shown in the Figma?

**Comment by dadiorchen** [comment]
https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap?node-id=2497%3A11584

**Comment by kenleyshaw** [comment]
Understood - I'll take a look at this and edit it later today!

**Comment by kenleyshaw** [comment]
@dadiorchen this took me a while because the SVG files from Figma were not working - I found that the only SVG files that seemed to work with MUI were the ones that were converted from Vectors, so I just used the vectors of zoom in, zoom out, and maximize in Figma and overlayed them on top of a custom button. Although the UI isn't exactly like the Figma one, its pretty similar. I messed around with custom Fabs, custom icons, custom hovers, but nothing seemed to do the trick besides changed the SVG files and creating a custom button!
Screen Shot 2022-04-28 at 5 04 23 PM

**Comment by dadiorchen** [comment]
I was thinking if we want to build a common component to do this (the floating button), we can use the component unit sandbox (there are some guides on this), to check the result rather than mount it in the real app, I saw you created a ColorButton, that's good, could put it into the separate file and create a unit test to present it, I need it works well in three envs: normal desktop env, mobile env, and dark desktop env, so cypress.viewport can chang the screen size for various devices, and to open dark mode, check  the code implementing the `theme` button on the top right conner.

**Comment by dadiorchen** [comment]
let me know if you need more support/resource on this.

**Pull request closed without merging**
