### PR TITLE
Feat/issue #430 dark theme

### LINKED ISSUE #430: A dark style theme of the whole app
Because we need to embed the map to other partners' websites/apps, we need to be able to switch to a dark style appearance. 

This is an example: https://www.treetown.finorx.com/map?tree_name=future-beautiful-green

image

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

### PR DESCRIPTION
**Pull request by VWRoli**
# Description

Add dark theme to the site. 
Created a themeContext to be able to handle the change between light and dark themes. Removed the old theme file.
Added a 'Theme' button to the Navbar where the user can change between themes. This can be changed to an icon or moved to somewhere else, it is just a temporary solution.
~~Added a temporary fix for the top page, which I commented out and should be removed after it gets fixed.~~
EDIT: Saw that it has been fixed, removed it.

Fixes #430

## Type of change

[comment]: # 'Please delete options that are not relevant.'

- [x] New feature (non-breaking change which adds functionality)

## Screenshots
Screenshot from 2022-02-09 09-05-03

Screenshot from 2022-02-09 09-05-06

Screenshot from 2022-02-09 09-05-17

# How Has This Been Tested?

- [x] Cypress integration
- [x] Cypress component tests

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by dadiorchen** [comment]
@VWRoli you are the legend!

**Comment by dadiorchen** [comment]
@VWRoli I have question, if you set the theme status in the context, what would happen if you refresh the page?

**Comment by VWRoli** [comment]
https://github.com/Greenstand/treetracker-web-map-client/blob/edf99b493071e4ac64af714efb830d1aea5e3f4f/src/context/themeContext.js#L7

Here we define the default theme. After refreshing the page this will be the theme value, whether we use the 'dark' or 'light' theme. 
If we want to keep the theme after refreshing the page, we need to add the value to localStorage. I can do that.

**Comment by dadiorchen** [comment]
@VWRoli to save some states for the web site becomes necessary now, I had another case need this feature too, I opened an issue on this: https://github.com/Greenstand/treetracker-web-map-client/issues/475

**Comment by QuaidBartolomei** [comment]
@VWRoli Fixes for the ci workflow have been merged upstream. Can you rebase this and resolve the conflicts?

**Comment by QuaidBartolomei** [comment]
I noticed some of the text is hard to read on the top.js page:

image

**Comment by dadiorchen** [comment]
But the example on MUI is perfect in dark theme?
image

**Comment by VWRoli** [comment]
That's because we use a custom theme with custom colors.
Right now, the setup is that we have two sets of colors for text. One set changes color based on the theme and one doesn't. 
The Chip text color is set to ` 'textSecondary.main'`, which does not change. This is necessary for components where we have a background that stays the same on both themes. 
The colors that are changing based on the theme are `theme.palette.text...`
The `theme.palette.textPrimary`, `theme.palette.textSecondary`, `theme.palette.textLight` are not changing.


I'll write something in the documentation so the devs know how to use the colors. And maybe come up with some more descriptive names for them too.

**Comment by VWRoli** [comment]
Also, I have some trouble working on the project @QuaidBartolomei. I have some problems with the API, maybe I need to set something for it to work, I'm not sure. I get some error messages.
Screenshot from 2022-02-19 17-21-44

**Comment by QuaidBartolomei** [comment]
@VWRoli I'm not encountering any issues on that page. You may need to run `npm install`

**Comment by VWRoli** [comment]
> @VWRoli I'm not encountering any issues on that page. You may need to run `npm install`

That's not the only page I'm encountering issues with. None of the API calls are working on my side for some reason. I'll try to look into it more... Only the home page is working, because there are no API calls there.
`npm i` or `update` did not solve the issue.
Screenshot from 2022-02-20 08-28-51

**Comment by QuaidBartolomei** [comment]
@VWRoli I think the issue might have been solved with this PR #477. Try merging the upstream changes and running `npm i` again. This will update your local dependency tree to the stable version of nextjs. 

Aside from that it also helps to know if you are using `npm run dev` or `npm run dev:mock`. The dev:mock script will use msw to intercept and mock the api calls.

**Comment by VWRoli** [comment]
After merging #447 and `npm i` `npm run dev:mock` is working, `run npm dev` does not.

The output is OK.

Although there is still an error on the top page with the below API call when using the mock server. The link returns 404. Not sure if it is related, but have to comment out `fetchCountries();` to be able to troubleshoot.

https://github.com/Greenstand/treetracker-web-map-client/blob/27445f1482405c99176245758e193787e57f3a72/src/pages/top.js#L37-L45
`https://dev-k8s.treetracker.org/webmap/countries/leaderboard` <== This one also returns 404.

Fixed the issues you mentioned though. 
Screenshot from 2022-02-21 18-18-34

**Comment by QuaidBartolomei** [comment]
@VWRoli Thanks for your help with troubleshooting this issue. The api route in the .env file needed to be updated, I submitted a fix here #480

**Review by QuaidBartolomei — APPROVED** [review]
Great work 🥇

**Comment by VWRoli** [comment]
> Great work 1st_place_medal

Thank you!

**Comment by dadiorchen** [comment]
@VWRoli I just checked this PR, it's perfect, thank you for you fantastic job!

**Pull request merged**
