### PR TITLE
refactor: iframe theme preview

### PR DESCRIPTION
**Pull request by RubenSmn**
# Description
Preview the theme does not reload whole Web Map anymore
Refactor to prevent duplication

## Type of change

[comment]: # 'Please delete options that are not relevant.'

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by dadiorchen** [comment]
@RubenSmn doesn't this mean we can quickly preview the result as we discussed in the meeting?

BTW, could you please merge the newest code from `beta` I fixed integration test CI

**Comment by RubenSmn** [comment]
@dadiorchen yes this means we can quickly preview the theme like discusssed in the meeting! I will merge the new tests.

**Comment by dadiorchen** [comment]
@RubenSmn this is really cool, I will download the code and try to play it

**Comment by RubenSmn** [comment]
@dadiorchen let me know if you find any bugs or improvements!

**Pull request merged**
