### PR TITLE
fix: photo of planter is missing #1509

### LINKED ISSUE #1509: The photo of planter is missing
https://beta-map.treetracker.org/planters/8843?bounds=46.35099649429322,-15.723825719803592,46.3587212562561,-15.716327922881064

image

If there isn't a photo for the planter, we should display a default picture here rather than a blank
---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- For design guidelines checkout our [Figma design](https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap).
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

### PR DESCRIPTION
**Pull request by 7pixel-cl**
# Description

[comment]: # 'Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.'
Add imagePlaceholder to Avatar component in case src is empty.

Fixes #1509
## Type of change

[comment]: # 'Please delete options that are not relevant.'

- [x] Bug fix (non-breaking change which fixes an issue)

## Screenshots

[comment]: # 'Please include screenshots of your changes if relevant.'

|       Before        |       After        |
| :-----------------: | :----------------: |
| "screenshot before" | "screenshot after" |
image|image

# How Has This Been Tested?

- [ ] Cypress integration
- [ ] Cypress component tests
- [ ] Jest unit tests

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by jeremydthomas** [comment]
Looks awesome to me. Approved! Interestingly enough his picture does work now :) I guess just one little thing that isnt even a big deal but on the fixes part make sure you put the number next to the # so I can easily click on the issue to see what we are trying to fix,  like this: fixes #1509, this will hyperlink it.

**Review by jeremydthomas — APPROVED** [review]

**Comment by dadiorchen** [comment]
@7pixel-cl Thank you I think this is good, just a thing strange to me is that why all your lines are different. I just see you changed to line, but the github show all lines changed.

**Comment by jeremydthomas** [comment]
@dadiorchen do you have any idea why this unit test has been running for over an hour?

**Comment by jeremydthomas** [comment]
@dadiorchen do you have any idea why this unit test has been running for over an hour?

**Comment by dadiorchen** [comment]
@jeremydthomas that's a problem that I don't know what causes it. We need someone help us fix it

**Pull request merged**
