### PR TITLE
fix: next asset path resolves #518

### LINKED ISSUE #518: Set up next.js to use relative path for resources
Generally, it's fine when we run the app locally, but when we deploy to the dev env, the next.js is trying to load resources from the root path, but because we run the app under `http://domain/web-map-site/` so this lead to 404 failed to load resources:

image

As shown above, we need the website to request: http://dev-k8s.treetracker.org/web-map-site/xxxx rather than http://dev-k8s.treetracker.org/xxxx

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

### PR DESCRIPTION
**Pull request by okdv**
# Description
Opened this one as a draft to make sure im understanding the issue correctly first/avoid dupe PRs. 
 
Interesting info @dadiorchen provided in that comment on my last PR #572 as i've never noticed this issue using basePath, however I dont have a ton of experience in nextjs. It seems that [assetPrefix](https://nextjs.org/docs/api-reference/next.config.js/cdn-support-with-asset-prefix) may be the desired outcome here, this will make sure next assets are prefixed with the same base path. e.g. /web-map-site/demo/ or /web-map-site/ or, in the case of env.development, directly to the base. 

Is this a correct understanding of the issue? or should the assetPrefix always be /web-map-site/ regardless of demo or local development? or something else? 

Fixes #518 

## Type of change
Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by dadiorchen** [comment]
Good, it's worth a try, I can set up the dev env using the way presented in your PR to see what will happen.

**Comment by okdv** [comment]
Sounds good @dadiorchen , I will go ahead and submit for review then

**Comment by dadiorchen** [comment]
@okdv some updates:

I did some investigation:

* Now we use `basPath` to set the folder behind the domain, for local, we use empty: basePath="" so the URL is: localhost:3000 for the dev env, we set to: web-map-site/demo/ so URL works: https://dev-k8s.treetracker.org/web-map-site/demo

* The link jumping in the pages works well, for code: 
```
      <Link href="/organization/1" >
        <ColorButton>{buttonText}</ColorButton>
      </Link>
```
will jump to: https://dev-k8s.treetracker.org/web-map-site/demo/organization/1 the basePath was added correctly.

* For the resource like js/css, it works as well: https://dev-k8s.treetracker.org/web-map-site/demo/_next/static/chunks/framework-5f4595e5518b5600.js

* But, there just one problem: 

```
import planterBackground from '../../images/background.png';
...
<img src={planterBackground} alt="profile" />
```

Doesn't work, the URL missed the basePath.

**Comment by dadiorchen** [comment]
profile
```

**Comment by okdv** [comment]
ahhhhh im finally getting it okay, sorry for all the misunderstandings. I was under the impression there were some rogue assets not getting prefixed somewhere. this can be solved with a redirect rule in the next.config.js -- submitting a new PR for this now

**Pull request closed without merging**
