### PR TITLE
feat: add timeline

### LINKED ISSUE #761: Restore the timeline feature
Try to restore the timeline feature, to do this, maybe we need to consider the UI/UX for this.

Please note, currently, because of performance consideration, we will just do the timeline feature for the global map, which means, on the org/planter/wallet page, say: /organizations/178 the user can not open the timeline and filter data by the data range ( which is too slow for the time being)

This is the old version of timeline:

Image

### PR DESCRIPTION
**Pull request by RubenSmn**
# Description
Add timeline feature, only desktop for now

Fixes #761

## Type of change

[comment]: # 'Please delete options that are not relevant.'

- [x] New feature (non-breaking change which adds functionality)

## Screenshots

[Kooha-2022-08-23-16:14:58.webm](https://user-images.githubusercontent.com/31519867/186181992-28e06a23-7dbc-4777-b056-d562a71c1d40.webm)

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by RubenSmn** [comment]
# Update
Add timeline for mobile
Add some input validation (start date can not be before end date and vice versa)

## Screenshots
[Kooha-2022-08-24-14:45:35.webm](https://user-images.githubusercontent.com/31519867/186422268-dec58c68-a349-4710-be6d-af3c369e78ce.webm)

**Comment by dadiorchen** [comment]
@RubenSmn nice work! would you integrate the timeline with the map object at this PR or you want to put into another way, some reminders:

To let the map render the timeline, put the filter with format as: timeline=2022_08_15-2022_08_16 
The previous version we put timeline into the URL, maybe we can do it the same or other better solution is welcome.

**Comment by RubenSmn** [comment]
@dadiorchen thanks! To keep the PR as small as possile I would like to open antoher one for the integration part

**Comment by dadiorchen** [comment]
@RubenSmn good, yea, let's go forwoard

**Pull request merged**
