### PR TITLE
feat: add prettier check to CI

### PR DESCRIPTION
**Pull request by ojafero**
# Checklist:

- [x] I have performed a self-review of my own code

### CODE REVIEW

**Comment by RubenSmn** [comment]
@ojafero could you check the error?

**Comment by ojafero** [comment]
@RubenSmn prettier wasn't applied to a component. I applied it  https://github.com/Greenstand/treetracker-web-map-client/pull/1235. The CI should pass now.

**Comment by RubenSmn** [comment]
Ah haha awesome so the Prettier test was working :smile:

**Review by RubenSmn — APPROVED** [review]

**Comment by dadiorchen** [comment]
@ojafero I added some change on this so now it is able to merge, thank you for your work!

**Pull request merged**
