### PR TITLE
fix: corrected the dates to when they were created

### LINKED ISSUE #929: Planter has been a Planter since todays date. This should be the date that he actually became a planter.
**Describe the bug**

Planter has been a Planter since todays date. This should be the date that he actually became a planter.

**To Reproduce**
(we recommend record a screenshot to show the case, like using http://loom.com to record)

Go to http://localhost:3001/planters/940

**Expected behavior**

The date should show when he became a planter, not todays date.

**Screenshots**
image

\*\* Node.js version
(The node version on your computer to run the project)

16.16

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome
- Version: Version 105.0.5195.102 (Official Build) (64-bit)

### PR DESCRIPTION
**Pull request by jeremydthomas**
# Description

[comment]: # 'Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.'

Fixes #929 

## Type of change

[comment]: # 'Please delete options that are not relevant.'

- [ x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Screenshots

image

# How Has This Been Tested?

- [x ] Cypress integration
- [ ] Cypress component tests
- [ ] Jest unit tests

# Checklist:

- [x ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by RubenSmn** [comment]
@jeremydthomas awesome job, the organization pages have the same issue. Could you also fix these?

**Comment by jeremydthomas** [comment]
@RubenSmn The API doesn't have the  .created_at option, or any time stamp option at all, I did look at that page as well.

**Comment by RubenSmn** [comment]
Ah okay cool thanks!

**Comment by jeremydthomas** [comment]
Do you think this is something that an issue should be raised on? The planter quote component has them, but all of the created_at's are null

**Comment by RubenSmn** [comment]
Might as well raise one, since we currently using dummy data I think we eventually want to use real data

**Comment by dadiorchen** [comment]
@jeremydthomas good job!

**Pull request merged**
