### PR TITLE
500 Error Fix

### LINKED ISSUE #1580: Set up next.js to do not redirect to `/500` when encountering 500 error
The `404` page is fine, as shown below:
image

But the `500` page will cause the redirection:
image
We need to show the 500 but remain on the original URL

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- For design guidelines checkout our [Figma design](https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap).
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

### PR DESCRIPTION
**Pull request by aayushgauba**
fixes #1580
Renders a React ErrorBoundry component as a fallback

### CODE REVIEW

**Comment by dadiorchen** [comment]
@aayushgauba how do you test this code? To reproduce the problem and test it?

**Comment by aayushgauba** [comment]
@dadiorchen Yes I threw a 500 error by adding this line of code in getServerProps
throw new TypeError("Ops, CMS didn't return a reasonable response.");

**Comment by dadiorchen** [comment]
@aayushgauba I downloaded your code and run it and add error code to the `top` page, but I still get the same result: the page was redirected to /500?

image

**Comment by aayushgauba** [comment]
@dadiorchen I don’t know why it does that. Let me take a look again.

**Pull request closed without merging**
