### PR TITLE
feat: add image for wallet page map

### LINKED ISSUE #1113: Image missing for wallet page
Image on bottom right on expanding web app is missing for wallet pages.

Screenshot
SCR-20221013-5b3

### PR DESCRIPTION
**Pull request by khalatevarun**
# Description

[comment]: # 'Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.'

Fixes #1113 

## Type of change

[comment]: # 'Please delete options that are not relevant.'

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Screenshots

[comment]: # 'Please include screenshots of your changes if relevant.'

|       Before        |       After        |
| :-----------------: | :----------------: |
|SCR-20221013-5b3|SCR-20221013-53h|

# How Has This Been Tested?

- [ ] Cypress integration
- [ ] Cypress component tests
- [ ] Jest unit tests

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by khalatevarun** [comment]
@dadiorchen please review.

**Comment by dadiorchen** [comment]
@khalatevarun please solve the conflict on the code.

**Comment by dadiorchen** [comment]
Sorry, @khalatevarun is this the same as https://github.com/Greenstand/treetracker-web-map-client/pull/1114?

**Comment by khalatevarun** [comment]
@dadiorchen this is for wallet.js page while #1114 is for token.js page
Will resolve the conflict

**Comment by khalatevarun** [comment]
Deleting due to too many conflicts. Raising a new branch to fix the issue.

**Pull request closed without merging**
