### PR TITLE
V2

### PR DESCRIPTION
**Pull request by DylanJG01**
# Description

[comment]: # Changes to cypress integration tests so they now pass. Change to  .env.developement. 

Fixes # 1724

## Screenshots

[comment]: # 'Please include screenshots of your changes if relevant.'

|       After        |
| :----------------: |
|Screenshot 2023-10-12 120229 |

# How Has This Been Tested?

- [x] Cypress integration

# Checklist:

- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by DylanJG01** [comment]
I consider this significant progress. I shall now fix what is wrong with the unit test.

**Comment by dadiorchen** [comment]
@DylanJG01 yes, there is a unit test failed, please check it.

**Comment by DylanJG01** [comment]
Solved.

**Comment by dadiorchen** [comment]
@DylanJG01 thank you!

**Pull request merged**
