### PR TITLE
fix: upgrade cypress action to try to fix ci problem

### PR DESCRIPTION
**Pull request by dadiorchen**

### CODE REVIEW

**Comment by jeremydthomas** [comment]
is this the fix for 
API CI for New Pull Requests / Install dependencies (pull_request) Failing after 6s?

**Comment by dadiorchen** [comment]
Thanks for looking at this, we got some really difficulty with the cypress test, I raise a question on their side: https://github.com/cypress-io/github-action/issues/922

**Comment by dadiorchen** [comment]
@jeremydthomas this is my fault, I have solved this, it is not the problem with cypress action.

**Comment by jeremydthomas** [comment]
> @jeremydthomas this is my fault, I have solved this, it is not the problem with cypress action.

Great to hear that you fixed it

**Pull request closed without merging**
