### PR TITLE
Reusable Image component 

### PR DESCRIPTION
**Pull request by pierrelstan**
# Description
Create a reusable image component that has:
- An icon indicating when do we take this photo
- A maximum icon that we can click to open a window displaying the full size of the picture.
- A like icon 

Fixes # (#311)

# How Has This Been Tested?

- [ ] Cypress integration
- [ ] Cypress component tests

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by dadiorchen** [comment]
@pierrelstan please solve the conflit in this PR ( in case you are not familiar with this), you can pull the web-map-site branch and merge/rebase from it, and solve the conflict locally then push this branch again)

Please attach a screenshot of your component

**Review by VWRoli — CHANGES_REQUESTED** [review]
Naming: it is a reusable image component, not a tree image component. The naming should reflect that. `CustomImageWrapper` or something.

In the commit message reference the issue number so it links it to that issue (or in the PR request? Not sure. Best if it's in both places).

Merge the web-map-site branch into yours as the theme got updated. (Typography and colors)

No need for the template literals here:
https://github.com/Greenstand/treetracker-web-map-client/blob/24f88ca15859f7adb3aa2e51639348427979a44b/src/components/common/TreeImage.js#L34

___

For texts use Typography, from MUI, not divs. With Typography, you can easily style the element, without adding classes. For example:
https://github.com/Greenstand/treetracker-web-map-client/blob/24f88ca15859f7adb3aa2e51639348427979a44b/src/components/common/TreeImage.js#L193
Could be  `<Typography variant="caption">Photo taken on</Typography>`

___

https://github.com/Greenstand/treetracker-web-map-client/blob/24f88ca15859f7adb3aa2e51639348427979a44b/src/components/common/TreeImage.js#L194-L196
Could be: `<Typography variant="h6">
              {dayOfWeek}/{month}/{year}
            </Typography>`

___

Here, Grid has its highly customizable properties. Add the alignments in line, also add the container property, and its child should be `<Grid item></Grid>` and not divs.
https://github.com/Greenstand/treetracker-web-map-client/blob/24f88ca15859f7adb3aa2e51639348427979a44b/src/components/common/TreeImage.js#L188

___

Don't hardcode the colors. Especially if you have to use it in three different places. If it is not in the theme put it somewhere where it is most logical. In this case, it's already in the theme `textPrimary`. The theme got updated from when you started this branch.

___

https://github.com/Greenstand/treetracker-web-map-client/blob/24f88ca15859f7adb3aa2e51639348427979a44b/src/components/common/TreeImage.js#L119

`wrapperFavorite` , `containerOpenWithOutlinedIcon`, `ContainerIcon` has a lot of common styles, which could be a common class, so we don't violate the DRY principle.
___

Don't bother with letterspacing, as I noticed in the Figma design letter spacing is quite universal, I will take a look at the theme, and add letterspacing globally, so in the future, we will not have to bother with it.

Margins and padding should be `theme.spacing()`, I'm guessing positioning items too.

___

Generally speaking good, job. The most important thing is to use MUI with all its power and customizability. You can get rid of a lot of hardcoded styles and classes by using MUI, which makes the code more readable.

**Comment by pierrelstan** [comment]
Screen Shot 2021-12-11 at 5 00 18 PM

**Review by VWRoli — CHANGES_REQUESTED** [review]
You can add a Typography element here and you can remove the class of the likes.
https://github.com/Greenstand/treetracker-web-map-client/blob/5fff591acb2aa14d3d22e01f91a6270655b8d0cf/src/components/common/CustomImageWrapper.js#L174-L176

Like this: `<Typography color="white">{likes}</Typography>`

___

On lines 86 and 95 you should use `theme.palette.common.white` instead of hardcoded color values.
https://github.com/Greenstand/treetracker-web-map-client/blob/5fff591acb2aa14d3d22e01f91a6270655b8d0cf/src/components/common/CustomImageWrapper.js#L86

Same goes for line 73:
https://github.com/Greenstand/treetracker-web-map-client/blob/5fff591acb2aa14d3d22e01f91a6270655b8d0cf/src/components/common/CustomImageWrapper.js#L73
This color is `theme.palette.textPrimary.main` with the opacity of 0.6
Again use the colors from the theme.

___

Also, I just realized that we can further improve the code. 
The wrappers/containers for the `likes`, `icon`, and `date` can be one common component. A component that accepts 4 positional (all of them optional) props. 

You can put it in the same file as we will only use it here. They are doing basically the same thing just in a different position.

And instead of having fixed widths, you can decrease the font size a little bit and adjust the padding/margin on small screens so it's more responsive.

Something like:
`<InfoWrapper top={1} left={1} right={1} bottom={1}></InfoWrapper>` 
(If you have a better name for it go for it)
You can position them like top={x} right={x}, and don't have to give them the left and bottom. (I think it's doable.)

Great job with the improvements by the way! Keep up the good work! Let me know if you have any questions.

**Comment by pierrelstan** [comment]
@VWRoli  thanks for the feedback.

**Comment by dadiorchen** [comment]
@VWRoli thank you for your great review and explanation! I also learned a lot!

**Review by VWRoli — APPROVED** [review]
Great job! Thanks for the improvements!

**Comment by pierrelstan** [comment]
> Great job! Thanks for the improvements!

The reviews and explanations helped me to get to that improvements.
 Thank you for leading me to do it the right way.

**Comment by dadiorchen** [comment]
Hey, @pierrelstan I just noticed that you are really using the cypress to build the test, that's a super good way to lead us to a higher standard! Thank you!

Just in case you are interested, this issue is about using cypress to build and check the logical of the filter component, the logic in this component would be more complicated. : ) https://github.com/Greenstand/treetracker-web-map-client/issues/340

**Comment by dadiorchen** [comment]
Just some suggestions/ideas about how to check the result of the test, I think the better way is to check some element that got semantic, rather than technical elements. 
A example for the former: planter avatar
A example for the later: 

The reason is that: the former is more worth checking, and the former would be more stable, so your test has higher possibility to survive along the way of iterations.

I remember there are some discussions in the testing-library document: https://testing-library.com/docs/queries/about/#textmatch

**Comment by pierrelstan** [comment]
> Hey, @pierrelstan I just noticed that you are really using the cypress to build the test, that's a super good way to lead us to a higher standard! Thank you!
> 
> Just in case you are interested, this issue is about using cypress to build and check the logical of the filter component, the logic in this component would be more complicated. : ) #340

@dadiorchen I'm interested in doing it. Assign it to me.

**Pull request merged**
