### PR TITLE
chore: set up the logo for web map client #1376

### LINKED ISSUE #1376: Set up the logo for web map client
Please set the logo on the banner, following the design here:

image
https://www.figma.com/file/LykDBRyuHY668vbGVkYaps/Greenstand-Webmap-(Copy)-(Copy)-(Copy)?node-id=2497%3A11570&t=j1Lif0cLx2tHeRcQ-4

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- For design guidelines checkout our [Figma design](https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap).
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

### PR DESCRIPTION
**Pull request by muhon9**
# Description

Changed the logo to treetracker logo

Fixes #1376

## Screenshoots

Screenshot 2023-02-19 at 7 59 51 PM

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### CODE REVIEW

**Comment by dadiorchen** [comment]
@muhon9 thank you for the contribution! A tiny thing, can you use SVG here? Because in this project, we prefer to SVG over PNG.

**Comment by muhon9** [comment]
@dadiorchen I will convert to SVG. I forgot to check for dark mode. Thanks for reminding me. Also, are we using the same logo or the greensand icon logo we previously used for mobile screens?

**Comment by dadiorchen** [comment]
@muhon9 exactly, this is a question, I will ask the designer to do a mobile version logo for us, before that, please use the previous one, I guess, does this make sense?

**Comment by muhon9** [comment]
@dadiorchen For mobile i kept the old one. For dark mode should we make the logo white? Also the check was failing for some reason
image (2)

**Comment by dadiorchen** [comment]
@muhon9 the designer has done for us, can you put the icon to the mobile version? https://www.figma.com/file/9qe1OgigmzRqVMHJK5FyJi/Greenstand-Webmap-(Copy)-(Copy)-(Copy)?node-id=4369%3A13184&t=yiZKShXXDRzaDM3d-4

**Comment by dadiorchen** [comment]
The CI problem is weird, the unit test get stuck, your code shouldn't cause this, I need to do some investigation

**Comment by muhon9** [comment]
@dadiorchen i have fixed the logo for mobile and dark mode. Please review and let me know if I need to make anymore change

**Comment by dadiorchen** [comment]
@muhon9 thank you!
@RubenSmn @jeremydthomas I remember we got a component to change the color of the SVG image, right? Is it useful for this case?

**Comment by dadiorchen** [comment]
If it is true, could you give some guide for this?

**Comment by jeremydthomas** [comment]
Yes, I believe you are right. I'll look for it.

**Comment by muhon9** [comment]
@dadiorchen I used two different SVG for two modes. It will be best if we can use the same SVG. If you can give me some hints I will do it

**Comment by RubenSmn** [comment]
Yes we've create a `CustomIcon`, check [here](https://github.com/Greenstand/treetracker-web-map-client/blob/beta/src/components/common/CustomIcon.js) for the source code.

**Comment by RubenSmn** [comment]
Maybe the issue of the CI getting stuck is due to our Node upgrade with [this commit](https://github.com/Greenstand/treetracker-web-map-client/commit/271d5afaa553806c15a55ce5862adba403a8e602)

**Comment by dadiorchen** [comment]
@muhon9 let's merge this, before that, can you solve the conflict above?

**Comment by muhon9** [comment]
@dadiorchen i have resolved the conflicts. As I am new to these things please inform me if I did anything wrong or if I have to do anything else

**Comment by dadiorchen** [comment]
@muhon9 thank you for your work! next time, you should use "feat:" for new feature and "fix:" for bug fix, your "chore" will not trigger release and then not put it into the changelog

**Comment by muhon9** [comment]
@dadiorchen Thank you.  I will keep it in mind in the following pull requests.

**Pull request merged**
