### PR TITLE
Walletid not match redirect 404 #1546

### PR DESCRIPTION
**Pull request by Harshalyadav**
# Description

If the wallet id is wrong or does not match with the database wallet id then it will show a 404 page.

### CODE REVIEW

**Comment by RubenSmn** [comment]
I think you should open against the `beta` branch instead of the `main` branch, correct @dadiorchen ?

**Comment by dadiorchen** [comment]
@Harshalyadav thank you for you contribution, really sorry we encounter some difficulty in maintaining the branches, now we have merged `beta` to `main`, but I don't know why there still are some many differences in this PR, I thought it should have gone if we merge it, so can you take a took at this, if there isn't better solution, I have to require you to checkout the main branch again, folk another branch then raise PR.
If you commit is valid, you can do this by `git cherry-pick [your commit]` to fetch that commit to your new branch

**Comment by dadiorchen** [comment]
By the way please check if those two other PR by you is valid (their name is similar)

**Comment by Harshalyadav** [comment]
ok, I check those PR.

**Comment by dadiorchen** [comment]
@Harshalyadav sorry, can you raise a new pr that just includes your solution (I guess is the line changing 500 to 404) so I can easily merge it? I will close this one, sorry for all these disturbing!

**Comment by Harshalyadav** [comment]
Ok, I'm creating new PR.

**Pull request closed without merging**
