### PR TITLE
Add Home link on navbar (mobile)

### LINKED ISSUE #1151: Add `Home` link to mobile navigation
# Description

Add a `Home` link on the mobile navigation. On the desktop version it is somewhat clear that you can click on the `Greenstand` text to go to the home page. On mobile this is not the case.

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- For design guidelines checkout our [Figma design](https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap).
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

### PR DESCRIPTION
**Pull request by ojafero**
# Description

Fixes #1151 

## Type of change

[comment]: # 'Please delete options that are not relevant.'

- [x] New feature (non-breaking change which adds functionality)

## Screenshots

[comment]: # 'Please include screenshots of your changes if relevant.'

mobile-navbar

# Checklist:

- [x] I have performed a self-review of my own code

### CODE REVIEW

**Comment by dadiorchen** [comment]
I think we should respect the UI design and hide the `Home` and just jump to home by touching the logo/icon?

**Comment by dadiorchen** [comment]
@ojafero did you suffer difficulty on the commit? I saw your PR includes change.md and package.json, you shouldn't need to do that, what's your steps to commit and create a PR?

**Comment by RubenSmn** [comment]
@dadiorchen @ojafero  I meant with the issue to add an extra button on the dropdown menu. Since it is not always clear that you can click on the icon.

**Comment by dadiorchen** [comment]
@RubenSmn I think that's fine, and the explicitly `home` text seems cumbersome.

**Comment by RubenSmn** [comment]
After a discussion in #1152 we decided against this change.

**Comment by RubenSmn** [comment]
After a discussion we decided against this change, thanks for the effort!

**Pull request closed without merging**
