### PR TITLE
Feat: location for planter info on org page

### LINKED ISSUE #947: Org page: location for planter info
Prerequisites: https://github.com/Greenstand/treetracker-query-api/issues/184

Image

### PR DESCRIPTION
**Pull request by khalatevarun**
# Description

[comment]: # 'Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.'

Fixes #947

## Type of change

[comment]: # 'Please delete options that are not relevant.'

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Screenshots

[comment]: # 'Please include screenshots of your changes if relevant.'

Not able to find planter quote in the org page to add screenshots of the changes.

# How Has This Been Tested?

- [ ] Cypress integration
- [ ] Cypress component tests
- [ ] Jest unit tests

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by khalatevarun** [comment]
@RubenSmn @dadiorchen please review following PR have added real location for planter info.

**Review by RubenSmn — CHANGES_REQUESTED** [review]
I think we need a more general approach here;
- if both present: `Country, Continent`
- if only one present: `Country` or `Continent`
- if none present: `Unknown`

Please check #1067

**Comment by khalatevarun** [comment]
Hey @RubenSmn , i have updated the changes please review.

**Review by RubenSmn — APPROVED** [review]

**Comment by dadiorchen** [comment]
@khalatevarun thank you a lot!

**Pull request merged**
