### PR TITLE
fix: update informationCard CSS to match figma

### LINKED ISSUE #300: UI refine for information card component
I guess these are just some margin, padding problems, (or maybe it's about making this component more responsive, I saw in the cypress sandbox, the component looks fine `npm run cyu`)

The design:
Screen Shot 2021-11-26 at 10 37 57 AM

The implementation:
Screen Shot 2021-11-26 at 10 38 23 AM

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.

### PR DESCRIPTION
**Pull request by jayeclark**
Signed-off-by: Jay Clark <jay@jayeclark.dev>

# Description

Updates InformationCard CSS to more closely match figma docs, and converts hardcoded values for font color and padding/margin to theme values where possible.

Fixes #300 

Screen Shot 2021-12-03 at 1 01 28 PM

## Type of change  
- [X] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?
- [X] Cypress integration
- [X] Cypress component tests

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by VWRoli — CHANGES_REQUESTED** [review]
Button text should have a color of textPrimary. Other than that good job!
`color: theme.palette.textPrimary.main,`

**Comment by jayeclark** [comment]
@VWRoli Thanks for the feedback, I've made those two corrections (the button font color changed between when I started working on the PR and when I merged recent commits on main, so I wasn't sure if the figma docs were changing and that was the new standard.) 

Letter spacing actually should be 0.02em (I tried 0.4em, but it does not match figma and ends up being way too spaced out.)

**Review by QuaidBartolomei — APPROVED** [review]

**Comment by VWRoli** [comment]
> Letter spacing actually should be 0.02em (I tried 0.4em, but it does not match figma and ends up being way too spaced out.)

Yes, sorry about that forgot a 0 there.

**Comment by dadiorchen** [comment]
@jayeclark thank your for your great job!

**Pull request merged**
