### PR TITLE
fix: added cursor pointer on slider hover

### PR DESCRIPTION
**Pull request by quyet-v**
# Description

[comment]: # 'Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.'

Made cursor turn into pointer when user hover over slider element.

Fixes (#703)

## Type of change

[comment]: # 'Please delete options that are not relevant.'

- [x] Bug fix (non-breaking change which fixes an issue)

[comment]: # 'Please include screenshots of your changes if relevant.'

# Checklist:

- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by dadiorchen** [comment]
@quyet-v thank you for your contribution!

**Comment by dadiorchen** [comment]
@quyet-v sorry I did something wrong with your PR, could you please remove my commit on top of you branch and raise your PR again?

**Comment by dadiorchen** [comment]
Sorry, I have meant to cancel the lockfile change, but I accidentally remove the whole file...

**Comment by quyet-v** [comment]
do I have to make another PR again?

**Comment by dadiorchen** [comment]
@quyet-v yes, please make another PR, please ignore my commit against your branch, and raise another one, let me know you have problem.

**Pull request merged**
