### PR TITLE
fix: format numbers on wallet page

### PR DESCRIPTION
**Pull request by ojafero**
# Description

Abbreviate numbers for CustomWorldMap on wallet page.

# Checklist:

- [x] I have performed a self-review of my own code

### CODE REVIEW

**Review by RubenSmn — CHANGES_REQUESTED** [review]
We should update the organizations detail page to adapt to this new functionality. Currently having a NaN bug.

http://localhost:3000/organizations/178

image

**Comment by ojafero** [comment]
@RubenSmn  Fixed it.
org

**Comment by dadiorchen** [comment]
@RubenSmn I think we can merge this now, right?

**Review by RubenSmn — APPROVED** [review]
Awesome work!

**Pull request merged**
