### PR TITLE
feat: render feature section only if data exists

### LINKED ISSUE #1072: Hide the featured section if it is empty
On the `top` page, it is possible that we won't display some of the featured sections:

Image

So add logic that if the featured array from API is empty,then hide this section.

### PR DESCRIPTION
**Pull request by khalatevarun**
# Description

[comment]: # 'Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.'

Fixes #1072 

## Type of change

[comment]: # 'Please delete options that are not relevant.'

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Screenshots

[comment]: # 'Please include screenshots of your changes if relevant.'

|       Before        |       After        |
| :-----------------: | :----------------: |
| "screenshot before" | "screenshot after" |

# How Has This Been Tested?

- [ ] Cypress integration
- [ ] Cypress component tests
- [ ] Jest unit tests

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by khalatevarun** [comment]
@RubenSmn @dadiorchen please review.

**Review by RubenSmn — COMMENTED** [review]
There are a lot of places that the `Featured` slider is being used.

I think we should handle the check "inline". Just pass in the trees or the organizations and let the component handle the check, return the slider if there is data else return null.

This does result in a new issue; the title will still be visible and will need the check anyway. I would like to suggest that we give the `Featured` slider a `title` prop and we display the title that way since the components/style for the title all seems to be the same.

@dadiorchen what do you think?

**Comment by khalatevarun** [comment]
@RubenSmn but if the trees/organisations data is empty then we will have to hide the title, so I think that the condition to hid the title depends on if the tree/organisation data is empty or not which is why we will have to keep it outside both the components.

**Comment by dadiorchen** [comment]
@khalatevarun I think the code is fine.

Yes, there is way to test it, for this `edge case` you can create a new integration test and MOCK the data to pass EMPTY list into the page (the `top.cy.js`)

**Comment by dadiorchen** [comment]
Would you like to try it? I mean, build the test to cover it?

**Comment by khalatevarun** [comment]
Sure @dadiorchen i would like to give it a try. Allow me some 2-3 days of time.

**Comment by khalatevarun** [comment]
@dadiorchen can we go ahead with this, couldn't find time for creating test case. Will definitely pick up later.

**Comment by dadiorchen** [comment]
@khalatevarun that's totally fine! Let's build test case for future case when it's getting really necessary!

**Pull request merged**
