### PR TITLE
feat: add custom Icon component

### LINKED ISSUE #994: UI: too big icon
The tree and group icon are too big, this happens somewhere else, please find the similar code and copy or maybe we can find a good way to reuse the code
https://prod-k8s.treetracker.org/web-map-beta/demo/planters/3939?keyword=undefined

Image

### PR DESCRIPTION
**Pull request by RubenSmn**
# Description
- Add custom Icon component
- Implement custom Icon in `CustomCard`
- Update `CustomCard` sx to iconProps to make the function/purpose more explicit
- Change `SvgIcon` to the custom Icon

Fixes #994 #843  #549

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Screenshots

[comment]: # 'Please include screenshots of your changes if relevant.'

|       Before        |       After        |
| :-----------------: | :----------------: |
| "screenshot before" | "screenshot after" |

# How Has This Been Tested?

- [ ] Cypress integration
- [ ] Cypress component tests
- [ ] Jest unit tests

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by dadiorchen** [comment]
@RubenSmn oh, there is a conflict after merging another pr

**Comment by RubenSmn** [comment]
@dadiorchen fixed it, we should use this for all the new icons. It automatically handles the responsiveness and if we want to change the icons we can do it in one place, keeping our UI very consistent!

**Comment by dadiorchen** [comment]
@RubenSmn really sorry! another conflict emerged! I tried to resolve it by myself, but it's too complicated for me

**Comment by RubenSmn** [comment]
@dadiorchen no worries, fixed it!

**Pull request merged**
