### PR TITLE
feat: new style of the Crumbs component

### LINKED ISSUE #875: Refine the layout/style of the breadcrumbs component
Please help to refine the `Crumbs` component, to:
* align all elements on the horizontal baseline (the bottom edge of the fonts)
* use appropriate font family/typography/font size for elements.

image

We can do this separate in the unit test file: Crumbs.cy.js : 

image

### PR DESCRIPTION
**Pull request by ar563**
# Description

- fixed typo in `Crumbs` component function name
- new style of the `Crumbs` component

Fixes #875

## Type of change

[comment]: # 'Please delete options that are not relevant.'

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Screenshots

Crumbs

# How Has This Been Tested?

- [x] Cypress integration
- [x] Cypress component tests
- [ ] Jest unit tests

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by dadiorchen** [comment]
@ar563 oh, I didn't know that mui get someone like this, thank you! 

@ar563 are you interested to join our slack community?

**Comment by dadiorchen** [comment]
@pierrelstan seems with the component by mui, this issue becomes easy

**Comment by ar563** [comment]
> @ar563 oh, I didn't know that mui get someone like this, thank you!
> 
> @ar563 are you interested to join our slack community?

I'm already on your slack

**Comment by dadiorchen** [comment]
@ar563 great! yes, this is a annoying problem, it is not so easy to link the user account between github and slalck, what's your name on the slack?

**Comment by ar563** [comment]
@dadiorchen Artur Bednarski

**Pull request merged**
