### PR TITLE
Added function to hide fullname

### PR DESCRIPTION
**Pull request by Niklas-dev**
I have added a function to hide the fullname of the planter. The function is taking in the fullname and returns the firstname and first letter of the lastname.

The edit is corresponding to the issue "Hide the full name of the planter"

- New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Review by dadiorchen — CHANGES_REQUESTED** [review]
@Niklas-dev I need you to do two extra things:
1. Use unit test to cover it, like: it('Dadior Chen should return Dadir C')
2. Apply this function to the planter page: http://localhost:3000/planters/940

**Comment by Niklas-dev** [comment]
Alright, will do it.

**Comment by Niklas-dev** [comment]
> 

This includes all the requested changes

**Comment by VWRoli** [comment]
The function could be simplified like this.
const hideFullName = (name) => `${name.charAt(0)}.`;

And I would also add a dot at the end so we know it is shortened.

Also if you create a PR please reference the issue, so others do not create a PR for the same issue. Like myself:D

**Review by VWRoli — CHANGES_REQUESTED** [review]
The function could be simplified like this.
const hideFullName = (name) => ${name.charAt(0)}.;

And I would also add a dot at the end so we know it is shortened. What do you think @dadiorchen?

Also if you create a PR please reference the issue, so others do not create a PR for the same issue. Like myself:D

**Comment by Niklas-dev** [comment]
Okay thanks for the feedback. Was my first PR.

**Comment by dadiorchen** [comment]
oh, @VWRoli you are right, I forgot the dot, thanks, guys.!

**Comment by Niklas-dev** [comment]
> Member

I have tried it but that way the first name is also hiding so its still more complex.

**Comment by VWRoli** [comment]
Take a look at this PR #447 I made, if something does not work you might find some good information there.

**Comment by Niklas-dev** [comment]
> Take a look at this PR #447 I made, if something does not work you might find some good information there.

Ah, now i got what you meant i thought about passing the full name to the function but you want just to pass the lastname.

**Review by jwgatt — APPROVED** [review]

**Comment by dadiorchen** [comment]
@Niklas-dev thanks, great job!

**Pull request merged**
