### PR TITLE
style: add white background to the logo in organization page

### LINKED ISSUE #280: UI/UX problem: who to deal with case like this:
On the organization page, we are showing an org called: 180earth like this:
Screen Shot 2021-11-11 at 4 58 35 PM

How could we deal with a case like this, to make the logo showing more nice and neat?

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.

### PR DESCRIPTION
**Pull request by pratikmdhr**
# Description
Added white background to the logo in the organization page for improved visibility

[comment]: # 280 

Fixes #280 

## Type of change

[comment]: # 'Please delete options that are not relevant.'

- [x] Bug fix (non-breaking change which fixes an issue)

## Screenshots 
logo-background-white

# Checklist:

- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by pratikmdhr** [comment]
I noticed for the main image behind the logo, the corners were not round like in the design (although border radius was applied in the code), so i added `overflow: 'hidden'` to the container for this image to fix it

**Comment by pratikmdhr** [comment]
Also noticed the image was being stretched since both `width` and `height` were set to 100%, is this fine?
stretched#280

**Comment by VWRoli** [comment]
> Also noticed the image was being stretched since both `width` and `height` were set to 100%, is this fine?

It is fixed in issue #379

**Comment by VWRoli** [comment]
> I noticed for the main image behind the logo, the corners were not round like in the design (although border radius was applied in the code), so i added `overflow: 'hidden'` to the container for this image to fix it

This is also fixed in #379

**Review by VWRoli — CHANGES_REQUESTED** [review]
Hello @pratikmdhr!
Thank you for your contribution.

> Fixes # (issue)

Should be Fixes #391 to be linked together.

Use theme.spacing() for margins, paddings and spacings, please. 
Color should come from the theme: `theme.palette.common.white`

**Comment by pratikmdhr** [comment]
> Hello @pratikmdhr! Thank you for your contribution.
> 
> > Fixes # (issue)
> 
> Should be Fixes #391 to be linked together.
> 
> Use theme.spacing() for margins, paddings and spacings, please. Color should come from the theme: `theme.palette.common.white`

Glad to help! 

I made the changes, let me know if anything..

**Comment by VWRoli** [comment]
The number should be 280, that's my bad. You want to link the issue # to this PR.

Love that you squashed your commits! Good job!

**Review by VWRoli — APPROVED** [review]

**Comment by pratikmdhr** [comment]
> The number should be 280, that's my bad. You want to link the issue # to this PR.
> 
> Love that you squashed your commits! Good job!



> The number should be 280, that's my bad. You want to link the issue # to this PR.
> 
> Love that you squashed your commits! Good job!

Oh yeah, i was about to ask you on that number.. modified it now..

Thanks!

**Comment by dadiorchen** [comment]
@VWRoli @pratikmdhr thank you all!

**Pull request merged**
