### PR TITLE
chore: draft facebook opengraph data for treetracker

### LINKED ISSUE #1260: Give suggestion on SEO and social media sharing and set up Open Graph
Please help us improve the SEO or social media sharing spreading on the internet for the web map client, set up like: Open Graph (https://ogp.me/) to utilize social media and search engines to promote the site.

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- For design guidelines checkout our [Figma design](https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap).
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

### PR DESCRIPTION
**Pull request by keyy123**
# Description

[comment]: # 'Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.'

Treetracker has made substantial progress overtime. Sometime soon, It will need to be shared with the world in order to actualize Green stand's mission statement. In order to improve the chance of succeeding, We need to market this application to potential users and generate relevant leads as much as possible. This is the issue that this PR attempts to solve.

In addition to this PR, Consider @ojafero PR #1293. I think it has the potential to ease the burden of adding all of tags if done right. Another alternative is to create additional API endpoints which will supply the data for SEO related events when fetched. 
Personally, I think the new head component and an update to API is the best action moving forward

Example: 

fetch('example.com/SEO') - many keys - map the results as keys on an object or an array and use them 

## THIS IS STILL A WORK IN PROGRESS. I AM MAKING A PR FOR ADDITIONAL FEEDBACK!

Fixes #1260

## Type of change

[comment]: # 'Please delete options that are not relevant.'

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)

## Screenshots

[comment]: # 'Please include screenshots of your changes if relevant.'

# How Has This Been Tested?

- [X] Cypress integration
- [X] Cypress component tests
- [X] Jest unit tests

# Checklist:

- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by dadiorchen** [comment]
This is great!

**Comment by keyy123** [comment]
@ojafero @dadiorchen Is my PR good? If not, I would appreciate feedback when you are available... 😅

**Comment by dadiorchen** [comment]
@keyy123 I will merge this PR, it's great, before that, can you help me solve the conflict above?

BTW, is it possible that we can test the result of this feature, after deployment to prod, by sharing things on twitter or so?

**Comment by keyy123** [comment]
Sure @dadiorchen. I'm dealing with a stomach bug but it is possible to do
so by going to twitters card validator

**Comment by dadiorchen** [comment]
@keyy123 good, take your time, and heal soon!

**Comment by dadiorchen** [comment]
This PR is meaningful for us, but for now, I want to hold on for a while, and do som basic SEO and website stat first, then consider adding this to do a comparasion.

**Pull request closed without merging**
