### PR TITLE
feat: showed planter info on top of tree page

### LINKED ISSUE #589: Context info for the planter's tree page
For this page:
http://localhost:3000/planters/940/trees/186734?embed=false

On the top of the tree info, display the planter's name and avatar, indicating this tree is under/planted by the planter.

Screen Shot 2022-05-23 at 10 32 29 AM

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

### PR DESCRIPTION
**Pull request by Mohmn**
# Description

[comment]: # 'Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.'

Fixes #589

## Type of change

[comment]: # 'Please delete options that are not relevant.'

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Screenshots
Screenshot from 2022-06-18 21-12-37

[comment]: # 'Please include screenshots of your changes if relevant.'

# How Has This Been Tested?

- [ ] Cypress integration
- [ ] Cypress component tests
- [ ] Jest unit tests

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Mohmn** [comment]
@dadiorchen planter info will only be shown for desktop devices, right?

**Comment by dadiorchen** [comment]
@Mohmn yes

**Comment by Mohmn** [comment]
@dadiorchen I have only added the changes for the desktop mode only, plz review It then?

**Comment by dadiorchen** [comment]
@Mohmn oh, I found you misunderstand the case, this case is a bit complicated, let me explain, there are two routers targeting to the same piece of code , the [treeid].js , by rewriteing the URL path:

http://localhost:3000/planters/940/trees/186734?embed=false
http://localhost:3000/trees/186734?embed=false

They got different meanings you know, the former is showing a tree under the context of a planter, the latter is just a single tree. the former is the case I mentioned in the issue #589 , we need to show planter info, but the second one doesn't.
If you don't get it, we can arrange a chat to figure it out. sure, it's a bit complicated :D

**Comment by Mohmn** [comment]
@dadiorchen I think i may have got your point
Screenshot from 2022-06-23 01-09-19

Screenshot from 2022-06-23 01-09-15

**Comment by dadiorchen** [comment]
@Mohmn great!

**Pull request merged**
