### PR TITLE
feat: add real location for org pages

### LINKED ISSUE #946: Need real location for org page
Prerequisites for this: https://github.com/Greenstand/treetracker-query-api/issues/185

Image

### PR DESCRIPTION
**Pull request by khalatevarun**
# Description

[comment]: # 'Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.'

Shows real location for org pages.

Fixes #946

## Type of change

[comment]: # 'Please delete options that are not relevant.'

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Screenshots

[comment]: # 'Please include screenshots of your changes if relevant.'

|       Before        |       After        |
| :-----------------: | :----------------: |
|190050779-4881b86c-735e-416d-b2e6-23313203a705|SCR-20221005-4od|

# How Has This Been Tested?

- [ ] Cypress integration
- [ ] Cypress component tests
- [ ] Jest unit tests

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by RubenSmn — CHANGES_REQUESTED** [review]
Same as with the #1059 I think we need a more general approach here;
- if both present: `Country, Continent`
- if only one present: `Country` or `Continent`
- if none present: `Unknown`

**Comment by RubenSmn** [comment]
@khalatevarun made this for you #1067

**Comment by khalatevarun** [comment]
thanks @RubenSmn will replace with this

**Comment by khalatevarun** [comment]
@RubenSmn I have made the required changes. Please review.

**Review by RubenSmn — APPROVED** [review]

**Pull request merged**
