### PR TITLE
feat: leaderboard component 

### PR DESCRIPTION
**Pull request by jwgatt**
In reference to  [#103](https://github.com/Greenstand/treetracker-web-map-client/issues/103)

image

I've created a draft of the profile component of the leaderboard for review, or if anyone want to use it. I'll continue building the other pieces in the meantime.

### CODE REVIEW

**Comment by dadiorchen** [comment]
@jwgatt what's your member name in greenstand slack?

**Comment by jwgatt** [comment]
> @jwgatt what's your member name in greenstand slack?

Jonny

**Comment by jwgatt** [comment]
**Update**
Screenshot from 2021-11-04 07-16-58

**Comment by dadiorchen** [comment]
beautiful, is it ready for merge?

**Comment by jwgatt** [comment]
I need to add the  leaderboard list component underneath, and make a few minor adjustments to these components here, but you could merge it while I finish the final part and I'll make a PR as soon as possible.

**Comment by dadiorchen** [comment]
thank you @jwgatt ! you helped a lot, to make sure we are on the same page, the newest design on leader board is changing to a frosted glass effect like this:
image

**Comment by jwgatt** [comment]
Is that component a slider now?

**Comment by jwgatt** [comment]
Screenshot from 2021-11-07 23-48-20

**Comment by dadiorchen** [comment]
@jwgatt it isn't a slider, just a static component, if you are speaking of the component for every country in the list below.

**Comment by jwgatt** [comment]
Added fix for [#273](https://github.com/Greenstand/treetracker-web-map-client/issues/273)

**Comment by dadiorchen** [comment]
@jwgatt what a beautiful PR, many thanks!

**Comment by jwgatt** [comment]
> @jwgatt what a beautiful PR, many thanks!

Happy to help!

**Pull request merged**
