### PR TITLE
fix: button element was not taking the full width made correct by add…

### LINKED ISSUE #1032: Wrong layout for the card button
https://prod-k8s.treetracker.org/web-map-beta/demo/planters/3350/trees/496170

Image

### PR DESCRIPTION
**Pull request by dharmiknotop**
…ing width 100%

# Description

[comment]: # 'Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.'

Fixes #1032  The button was not taking up the whole space because of the parent link so gave the parent link width : 100% which enabled the button to take up the whole space

## Type of change

[comment]: # 'Please delete options that are not relevant.'

- [ ] Bug fix (non-breaking change which fixes an issue)

## Screenshots

[comment]: # 'Please include screenshots of your changes if relevant.'

|       Before        |       After        |
| :-----------------: | :----------------: |
| 193157928-431853e5-38f8-4d9d-9b2a-8018bb09a742 | image |

image

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] My changes generate no new warnings

### CODE REVIEW

**Comment by dadiorchen** [comment]
@RubenSmn oh, Ruben, is this related to the change on the link? I remember a volunteer changed the Link component, the interesting thing is, it just break the prod version...

**Comment by dadiorchen** [comment]
@dharmiknotop thanks! good catch!

**Comment by dharmiknotop** [comment]
thanks!

**Comment by RubenSmn** [comment]
@dadiorchen yes it is, all the links are affetced by that change. I made a PR to revert

**Comment by dharmiknotop** [comment]
so, is the issue fixed @RubenSmn?

**Comment by RubenSmn** [comment]
Yes this issue was caused by another PR, we will revert that change so this issue does not exist anymore

**Pull request closed without merging**
