### PR TITLE
Added flag icons in .svg format

### PR DESCRIPTION
**Pull request by Koda-Pig**
Downloaded all flags from https://flagicons.lipis.dev/ and added them to the src/pages/flags directory.
Included 1x1 and 4x3 aspect ratios.
Renamed all flags from their 2 letter code to the full name.

Fixes this issue: https://github.com/Greenstand/treetracker-web-map-client/issues/298

### CODE REVIEW

**Comment by dadiorchen** [comment]
@Koda-Pig great job!
Did you try to visit the flag in the next.js, I mean, like, `npm run dev` then visit: http://localhost/1x1/China.svg?  does it work?

**Comment by Koda-Pig** [comment]
Thanks! I did not try that before I made this pull request. I have moved the files to the public directory, so now it works to visit:
http://localhost:3000/images/flags/4x3/china.svg

I kept getting an error when I was trying to update this pull request, so I created a new one here: https://github.com/Greenstand/treetracker-web-map-client/pull/351

**Comment by VWRoli** [comment]
Shouldn't we just install it as an npm package instead of storing them in our code @dadiorchen?

**Comment by dadiorchen** [comment]
@VWRoli what's your idea of npm package? is there any package for this?

**Comment by dadiorchen** [comment]
Yes, it's good for reuse if we pack them into lib

**Comment by VWRoli** [comment]
We can install the flags from the link via npm, it says in the documentation.
`npm install --dev flag-icon-css`

**Comment by dadiorchen** [comment]
@VWRoli oh, I didn't realize that this is a module, but, why `--dev`?

@Koda-Pig yes, it should be better to just install that lib, can you change to use it?

**Review by dadiorchen — CHANGES_REQUESTED** [review]
change to install the lib

**Comment by VWRoli** [comment]
> @VWRoli oh, I didn't realize that this is a module, but, why `--dev`?

No clue. That's what the documentation said.

**Comment by Koda-Pig** [comment]
@dadiorchen, I removed the flag icons from the public directory and added them as an npm package, but I have not made the commit yet as I get the same error again.

@VWRoli the error I get when I try to commit the changes is:

```
/usr/bin/env: ‘bash’: No such file or directory
husky - pre-commit hook exited with code 127 (error)
```

**Comment by VWRoli** [comment]
>  @VWRoli the error I get when I try to commit the changes is:

Check this out: 
https://github.com/typicode/husky/issues/1038
Probably this is your problem.

**Comment by Koda-Pig** [comment]
@VWRoli I've looked at that, but I don't know what this means:


```
Hi all,

You need to update your PATH on Windows to properly target cygpath executable, which was in my case, the main problem.
Just add C:\Program Files\Git\usr\bin\cygpath.exe to you PATH environment variable and it should work perfectly 😉

Try and let us know.
```

Please can you explain

**Comment by VWRoli** [comment]
> @VWRoli I've looked at that, but I don't know what this means:
> 
> ```
> Hi all,
> 
> You need to update your PATH on Windows to properly target cygpath executable, which was in my case, the main problem.
> Just add C:\Program Files\Git\usr\bin\cygpath.exe to you PATH environment variable and it should work perfectly 😉
> 
> Try and let us know.
> ```
> 
> Please can you explain

You have to add this line to your PATH env variable `C:\Program Files\Git\{your user name}\bin\cygpath.exe` which should fix the issue you are having. If you have Win 10:
https://www.architectryan.com/2018/03/17/add-to-the-path-on-windows-10/

**Comment by Koda-Pig** [comment]
Thank you @VWRoli - I followed those instructions, restarted my PC but I still get the same error.

I know I can get around it by just making a new pull request. Should I do that?

**Comment by VWRoli** [comment]
> Thank you @VWRoli - I followed those instructions, restarted my PC but I still get the same error.
> 
> I know I can get around it by just making a new pull request. Should I do that?

Sure, do that. Close the ones you already opened. 

But just out of curiosity. When do you get the error, git commit or git push?

**Comment by dadiorchen** [comment]
@Koda-Pig if you are in some difficulty, you can also catch me online, or join the weekly meeting or sunday's co-work for help

**Pull request closed without merging**
