### PR TITLE
fix: impact section icon heights

### LINKED ISSUE #785: These two icons are too big on mobile
Check our figma design to check the correct size, and set it in the code. https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap?node-id=4355%3A15745

### PR DESCRIPTION
**Pull request by RubenSmn**
# Description

Changed the height of the icons to be responsive
Fixes #785

## Type of change

[comment]: # 'Please delete options that are not relevant.'

- [x] Bug fix (non-breaking change which fixes an issue)

## Screenshots
Desktop
|Before
|:-:
|localhost_3000_trees_186735_embed=false (1)
|After
|localhost_3000_trees_186735_embed=false

Mobile
Before|After
:-:|:-:
localhost_3000_trees_186735_embed=false(Samsung Galaxy S8+) (1)|localhost_3000_trees_186735_embed=false(Samsung Galaxy S8+) (2)

# Checklist:

- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by dadiorchen** [comment]
@RubenSmn did you put it in a wrong order? I mean the picture for mobile version.

**Comment by RubenSmn** [comment]
@dadiorchen yes I did, sorry!

**Comment by dadiorchen** [comment]
@RubenSmn can you get rid of the conflict above?

**Comment by RubenSmn** [comment]
@dadiorchen fixed it

**Pull request merged**
