### PR TITLE
Test: Fix cypress w/ nock implementation and PR workflows

### PR DESCRIPTION
**Pull request by QuaidBartolomei**
# Description

- fix tests that were not passing with `npm run cy:nock`	
- refactor cypress tests with reuseable `prepareNocks()` function
- use mocked integration tests in pr workflow
- refactor SSR functions to use api helper functions and utilize `Promise.all` for faster page loading.

## Notes for other developers

- The `dev:mock` script now uses msw for API mocking, routes can be added/changed in the `src/mocks/handlers.js` file.
- Use `cypress:run:fast` to quickly run all integration tests with mocked API.
- To quickly add existing mock routes to your integration tests use the `prepareMocks()` or `getNockRoutes()` functions in `cypress/tests/integration/nockRoutes.js`. 
  - These functions can be passed tree, organization, and/or planter objects to control the mock data that is returned. Incomplete data objects can also be passed and the other fields will be filled in with default data. See existing integration tests for examples.

## Todo

- [x] Update readme
- [x] get workflows to pass when using mocked api

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by QuaidBartolomei** [comment]
The tests are passing for me locally but this issue keeps appearing in the ci 

```
The following error was thrown by a plugin. We stopped running your tests because a plugin crashed. Please check your plugins file (`/home/runner/work/treetracker-web-map-client/treetracker-web-map-client/cypress/plugins/index.js`)

 Error: ENOENT: no such file or directory, open '/home/runner/work/treetracker-web-map-client/treetracker-web-map-client/.next/cache/images/IGC6G1Grw7zu8lzcwQ8p0YHQGVr1lHoXWqevQX2zeKI=/0.1644487343288.9stqc8mi95e7STby2fXD5h+rhiCmvLGiYDCVA7cZ2dU=.webp'
error - uncaughtException: Error: ENOENT: no such file or directory, open '/home/runner/work/treetracker-web-map-client/treetracker-web-map-client/.next/cache/images/IGC6G1Grw7zu8lzcwQ8p0YHQGVr1lHoXWqevQX2zeKI=/0.1644487343288.9stqc8mi95e7STby2fXD5h+rhiCmvLGiYDCVA7cZ2dU=.webp'
```

This error also sometimes occurs locally and I have to delete the `.next/` dir before running the tests again. I think this is an issue with starting the nextjs dev server in `cypress/plugins/index.js` which is a requirement for being able to configure the nock intercepts within the cypress integration tests. I have tried a few different solutions but none of them fixed the error:

- remove image mocking
- remove cypress-watch-and-reload plugin
- use different test script in the workflow

**Comment by QuaidBartolomei** [comment]
I noticed the same issue was occurring with #474. I was able to fix the issue on that PR by running the tests against the pre-built production server instead of the dev server. It seemed that the issue was with the Nextjs dev server so I tried updating this PR to the latest nextjs pre-release and now the checks pass.

**Comment by QuaidBartolomei** [comment]
Looks like it's working now, updating nextjs to the v12.11 pre-release was the solution.

**Comment by dadiorchen** [comment]
@QuaidBartolomei thanks for this huge contribution. sorry about seeing you close your msw PR, that's also a big effort!

About the Promise.all, sounds great, I also heard people talking about https://react-query.tanstack.com/

**Comment by dadiorchen** [comment]
> 



> I noticed the same issue was occurring with #474. I was able to fix the issue on that PR by running the tests against the pre-built production server instead of the dev server. It seemed that the issue was with the Nextjs dev server so I tried updating this PR to the latest nextjs pre-release and now the checks pass.
> 
> edit: now the tests are still passing but it is taking a very long time 😕

Slow is better than none, great!

**Comment by dadiorchen** [comment]
I have two questions:
1. Are we using nock and msw both? How does it work?
2. In this way, is there an example of mock special data for a single integration test case?

**Comment by QuaidBartolomei** [comment]
> About the Promise.all, sounds great, I also heard people talking about https://react-query.tanstack.com/

I've used react-query before to handle client-side API calls. It looks like it can also be used with Nextjs SSR to present the client with a placeholder page that is replaced/filled-in with the API data as it arrives. https://react-query.tanstack.com/guides/ssr

>sorry about seeing you close your msw PR, that's also a big effort!

Most of the work from the msw branch also exists in this branch. In any case, working on the msw branch helped me determine that the nextjs package was causing the issues. 

> Are we using nock and msw both? How does it work?

I kept msw because I already wrote the route handlers and it can still be used to handle mocking on the dev server. Nock may be able to also replace this functionality, but I was not certain how to handle both the server-side and client-side API calls from the nextjs app. 

> In this way, is there an example of mock special data for a single integration test case?

All of the integration tests are passing specific data to the `prepareNocks()` function. Here is a snippet of the function to demonstrate how it handles data parameters:

```js
```

> Slow is better than none, great!

Don't worry, the durations are back to normal. It was being caused by separate change I made.
image

**Comment by dadiorchen** [comment]
Thanks!

**Pull request merged**
