### PR TITLE
style: issue #383 information card background color

### LINKED ISSUE #383: Information card background color does not match design
Information card background color does not match the Figma design.
Looks like this:
Screenshot from 2021-12-26 16-35-11

Should look like this:
Screenshot from 2021-12-26 16-35-09

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

### PR DESCRIPTION
**Pull request by VWRoli**
# Description

 Information card background color design.

Fixes #383
## Type of change

[comment]: # 'Please delete options that are not relevant.'

- [x] Bug fix (non-breaking change which fixes an issue)

## Screenshots 

Screenshot from 2021-12-26 16-38-30

# How Has This Been Tested?

- [x] Cypress component tests

# Checklist:

- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by QuaidBartolomei** [comment]
@VWRoli Please rebase this so we can use the new PR workflow testing 😃

**Review by QuaidBartolomei — CHANGES_REQUESTED** [review]
The component test should be updated to include both color variations and prove that the color changes when it should.

**Comment by dadiorchen** [comment]
@QuaidBartolomei in my option, we don't need to cover all edge cases for component/unit test, it brings too much effort to write the code, and more important, to maintain it in the future.

**Comment by QuaidBartolomei** [comment]
@dadiorchen True, I don't want to be too demanding with my requests for changes. In this case I opened the component tester to view the component and it felt very lacking without the other color option being displayed. Also the condition for applying the inverted color was very specific so I thought a test to ensure it keeps working would be appropriate.

**Comment by dadiorchen** [comment]
@VWRoli what's your take?

**Comment by VWRoli** [comment]
I'm not sure, to be honest. I don't know much about testing, what should be tested and what shouldn't be tested. It is definitely on my list of things to learn more about testing and learn Cypress at least on a basic level.

**Comment by dadiorchen** [comment]
I will merge this at this point, let's thinking this along the way

**Pull request merged**
