### PR TITLE
Feat: add new badge on [captureid] page to check tree match status

### LINKED ISSUE #1586: Add `tree-matched` badge on the `/captures/{id}` page
UX: to the right of the `token not issued` badge, add a new badge, which:
* If the `capture` object's `tree_id` is not null, then the badge shows: `tree matched` with primary `green` color, and by clicking the badge, the page jumps to: `/trees/{tree_id}`
* If the `tree_id` is null, then the badge shows: `waiting for tree match` in grey color

http://localhost:3000/v2/captures/0c2d6e3a-d02a-4edf-bcdc-893e1f7a4817

image

---
some hints:
- Dev guides for `v2` feature: https://docs.greenstand.org/web-map/v2-web-map
- If you want to join the Slack community (some resources need the community member's permission), please leave your email address.

### PR DESCRIPTION
**Pull request by khalatevarun**
# Description

[comment]: # 'Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.'
* Add tree-matched batch
* The batch will be displayed only when showTreeMatchStatus is passed since it is also used on treeid page where we don't need to show.

Fixes #1586 

## Type of change

[comment]: # 'Please delete options that are not relevant.'

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Screenshots

[comment]: # 'Please include screenshots of your changes if relevant.'

### When tree.id is undefined or does not exist
image

### When tree.id exists
image

# How Has This Been Tested?

- [ ] Cypress integration
- [ ] Cypress component tests
- [ ] Jest unit tests

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by khalatevarun** [comment]
@dadiorchen please have a look, let me know if my approach is good or needs to changed.

**Comment by khalatevarun** [comment]
@RubenSmn can you have a look at it once?

**Comment by khalatevarun** [comment]
@dadiorchen can we merge this PR or does it need any changes or improvement?

**Comment by dadiorchen** [comment]
@khalatevarun this Badge component is getting unnecessarily complicated now, do you think we can do a refactor to make it more reusable? The problem is that the component knows too much, like: `tokenId`, if we can remove all those things, maybe we can make it simple and easy to reuse.

**Comment by RubenSmn** [comment]
Ye I was thinking about this too, but didn't know if we wanted to introduce a new feature and a refactor in the same PR.

As for the refactor I think it would be nice to have separate badges, say a `VerifiedBadge` and a `MatchStatusBadge` which we can use individually instead of one `Badges` component. I think this makes more sense in terms of the component hierarchy and readability.

**Comment by dadiorchen** [comment]
@khalatevarun I hope you can do this refactor in the `main` branch and sync code to the v2 later, because accurately, this doesn't belong to `v2` and would cause conflict in the future if we do it on v2.

**Comment by dadiorchen** [comment]
@RubenSmn is it possible to create a general `badge` component, and leave the client to decide the details? so the `badge` just communicates with the invoker by: text, color, icon?

**Review by RubenSmn — COMMENTED** [review]
@khalatevarun I think this solution introduces less readable code. I think we should explore something like a `variant` prop to make a generic `Badge` component.

Usage of that component could be something like this:

```javascript
<Box>
  <Badge variant="verified">
    {tree?.approved ? "Waiting for verification" : "Verified"}
  </Badge>
</Box>
```

And then in the `Badge` component we do something like this:

```javascript
const badgeProps = {
  verified: { styles, icon, etc },
  "awaiting-approval": {},
  "other-variants": {},
};

function Badge({ variant, ...rest }) {
  const props = badgeProps[variant];

  return <Chip size="small" {...props} {...rest} />;
}
```

So we make one generic `Badge` component instead of specific badges. This allows also for easy scaling since we can simply add a new `variant`.

**Comment by khalatevarun** [comment]
@RubenSmn i think one of the reasons why we build reusable component is too have the same design of the component across the application, if we expose too many control to the parent component using it then there is not sense in making it reusable, we can rather directly go with Chip instead of wrapping it with HOC.

In PR - 1643, I have tried to expose only event handlers and some variables to change status keeping other attributes private to the Badges component, does it make sense?😅

**Comment by RubenSmn** [comment]
I have to disagree here @khalatevarun, we provide a singe prop `variant` which defines a preset of properties which are needed for a single **variant**, this abstracts a lot of things like style and icons. We allow for a **opt-in** to add more props as needed, say a `onClick` event.

**Comment by dadiorchen** [comment]
I feel a styled `chip` is good enough, I prefer to give back some responsibility to parents to describe things, but I admit this is a trade-off

**Comment by khalatevarun** [comment]
Closing this PR since no change are required as the PR to fix this issue was merged to main and then to v2

**Pull request closed without merging**
