### PR TITLE
Image url fix - resolves #518

### LINKED ISSUE #518: Set up next.js to use relative path for resources
Generally, it's fine when we run the app locally, but when we deploy to the dev env, the next.js is trying to load resources from the root path, but because we run the app under `http://domain/web-map-site/` so this lead to 404 failed to load resources:

image

As shown above, we need the website to request: http://dev-k8s.treetracker.org/web-map-site/xxxx rather than http://dev-k8s.treetracker.org/xxxx

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

### PR DESCRIPTION
**Pull request by okdv**
# Description

After some misunderstanding of the issue I finally see whats going here. I went ahead and went with the least intrusive method and fixed with a redirect rule in the next.config.js 

There are other ways to fix this as well (such as a middleware component for the image), but this seems easiest and lightest to me. I checked several pages where this was broken and verified they are working now. 

Fixes #518

## Type of change

Bug fix (non-breaking change which fixes an issue)

## Screenshots

Example
2022-05-24 00 13 08 localhost 2d3293202bc9

### CODE REVIEW

**Comment by Davidezrajay** [comment]
@okdv thanks for your awesome work! Reach out if you want to join us on Slack as well **info (AT) greenstand.org**

**Comment by dadiorchen** [comment]
@okdv love the hack style.

Could you please help to do a production env test for this, the steps:

1. Set the bashPath in .env.production (please use a folder so we can check the case similar to online env)
2. run command: npm run build
3. run command: serve build
4. visit and test on: http://localhost/web-map-site/

I want to check if it works on the prod env, and if the image URLs are correct.

**Comment by okdv** [comment]
@Davidezrajay @dadiorchen thanks y'all and will do!

as for the prod test, i didnt test using serve (doesnt seem to be setup for serve?), but I did using `next build & next start` and it seems to be working ok. I ran some cypress tests as well and confirmed there arent any errors or 404s popping up around it. this screenshot is from that production build and shows the image in question was grabbed over a 304 redirect.

2022-05-24 15 41 59 localhost beb58c0e160d

**Comment by dadiorchen** [comment]
@okdv you are awesome! I will merge your PR soon

**Comment by dadiorchen** [comment]
@okdv if you want, I can invite you to our slack community through email

**Comment by dadiorchen** [comment]
By the way, we did some update on the package-lock.json, can you update an push again, see conflict above

**Comment by okdv** [comment]
Thanks for the heads up @dadiorchen , got the conflict resolved now

And that sounds good to me! I expect to contribute a good bit in the near future, my email is okd@otho.dev

**Comment by dadiorchen** [comment]
I believe we have soled this problem, now we can close this PR.

**Pull request closed without merging**
