### PR TITLE
feat: implemented wallet page

### LINKED ISSUE #592: Implement the /wallets/[walletName] page
This page will present the wallet: wallet name, logo

We will re-use the planter page design for this implementation: https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap?node-id=4819%3A14477

The API is ready: https://github.com/Greenstand/treetracker-query-api/blob/main/__tests__/e2e/wallets.spec.ts

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

### PR DESCRIPTION
**Pull request by Mohmn**
# Description

[comment]: # 'Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.'

Fixes #592

## Type of change

[comment]: # 'Please delete options that are not relevant.'

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Screenshots

[comment]: # 'Please include screenshots of your changes if relevant.'

# How Has This Been Tested?

- [x] Cypress integration
- [ ] Cypress component tests
- [ ] Jest unit tests

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by dadiorchen** [comment]
@Mohmn this is awesome! Because our integration test CI is broken, so I can not check the screenshot of this page, could you please paste some here? We need to check if it is okay in dark/light/mobile env. Thank you! This is huge progress, and sorry about the cumbersome asking you to do screenshot , the CI is broken, we are trying to fix it.

**Comment by Mohmn** [comment]
@dadiorchen 
desktop
Screenshot from 2022-06-29 00-21-51
Screenshot from 2022-06-29 00-21-48
Screenshot from 2022-06-29 00-21-45
Screenshot from 2022-06-29 00-21-39
Screenshot from 2022-06-29 00-21-36
Screenshot from 2022-06-29 00-21-31

**Comment by Mohmn** [comment]
@dadiorchen 
mobile 
Screenshot_2022-06-29-00-15-47-478_com android chrome
Screenshot_2022-06-29-00-15-38-827_com android chrome

**Comment by dadiorchen** [comment]
@Mohmn this is really beautiful!

**Comment by dadiorchen** [comment]
@Mohmn do we have plan on the small world map?

**Comment by Mohmn** [comment]
> @Mohmn do we have plan on the small world map?

What do you think about showing tree data(tree_location and total no of trees) connected to wallet id

**Comment by dadiorchen** [comment]
I think they are similar as the planter/org pages, the map could show: 
100 (token/tree in) Africa
80 (token/tree in) North Ameriac
...

image

what do you think?

**Comment by dadiorchen** [comment]
We need to map the token to tree, so we can statistic the number by location/continent

**Comment by dadiorchen** [comment]
@Mohmn just some hint, in the GET countries/leaderboard endpoint, there are some code I thought might be similar, to statistic the total number according to the area.

We have different levels of area: country, continent, city, so you need to filter the data by correct area type I guess.

**Pull request merged**
