### PR TITLE
Material-UI 5, React 17, Nextjs 11 migration

### LINKED ISSUE #255: Some problem when auto-refreshing the page by next.js dev mode.
When modifying js file, next.js will automatically reresh the web page, but sometimes it show error:
image

This is related to the map object mounting to the DOM, maybe we need a better way to mount the map object to the DOM

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.

### PR DESCRIPTION
**Pull request by QuaidBartolomei**
# Description

The goal is to allow our existing codebase which is using Material-UI v4's makestyles to still render correctly while new components can be built with the new emotion styling engine. [tss-react](https://www.npmjs.com/package/tss-react) was used for this. Check `src/models/makeStyles.cy.js` for a component test that shows makeStyles and sx working together.

- Fixes #255
- Updates NextJs to help with #233

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# How Has This Been Tested?

- [x] Cypress Integration
- [x] Cypress Component
- [x] Jest

# Checklist:

- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by dadiorchen** [comment]
I like the todo list style in the PR, Github shows a circle progress icon in the PR list

**Comment by dadiorchen** [comment]
@QuaidBartolomei I think it's fine that we just push this forward at a bigger pace. just upgrade and resolve the import and merge it first, then we raise PR to fix problems, consideration of mine is that if you leave this behind the main branch then it gets you hard to catch up and resolve conflict. What do think?

**Comment by dadiorchen** [comment]
Buy the way, I'd like to try the `sx` props earlier :D

**Comment by QuaidBartolomei** [comment]
I think this branch is still too broken to be merged in. I don't have tss-react, mui5 and nextjs all configured to work together.

**Comment by QuaidBartolomei** [comment]
@dadiorchen I spent some time on this and got it working nicely. There may be some small issues but I think it is ready for merge. I created a new component test to show the sx prop working with makeStyles.

**Comment by dadiorchen** [comment]
Thanks verymuch Super great job!

**Pull request merged**
