### PR TITLE
fix: clicking between token icons updates the url

### LINKED ISSUE #1703: Clicking token icon doesn't work
On this page: https://map.treetracker.org/tokens/254fd088-b0aa-4eef-a3d9-b02c491ff9d3?bounds=47.21599817276002,-18.561482861162506,47.2314476966858,-18.54671429311487

Clicking other token icon on the map doesn't change the page to token clicked.
image

But on this page for tree point, it works.

https://map.treetracker.org/trees/5442304

### PR DESCRIPTION
**Pull request by henlam1**
# Description

- Previously, the same URL was reused when we clicked on new tokens
- To update the URL, we needed the token id of the new tree we clicked on
- Getting the token id was possible with the query API

Fixes #1703 

## Type of change

[comment]: # 'Please delete options that are not relevant.'

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- [ ] Cypress integration
- [ ] Cypress component tests
- [x] Jest unit tests

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by dadiorchen** [comment]
@henlam1 thank you, this is good! I have some suggestion, the api call bring in [side effect](https://en.wikipedia.org/wiki/Side_effect_(computer_science)) to the path resolver, we should avoid this, and also, the signature of the function changed, it also brings some risk.

How about this, we add a new parameter (wholeTree) as the last parameter, and request the api before calling the function, and pass the result to it.

**Comment by henlam1** [comment]
@dadiorchen Thanks for the suggestions! I was unaware of the side effects and risks of the API/async before.

In my latest commit I followed your advice and passed the wholeTree object into the getPathWhenClickTree function in pathResolver.js. As a result, handleClickTree in App.js now calls the API instead.

I also corrected the logic for creating oken paths.

**Comment by dadiorchen** [comment]
@henlam1 thank you for your contribution!
Are you interested ton join our community?

**Comment by dadiorchen** [comment]
You can leave you email so I can invite you

**Pull request merged**
