### PR TITLE
Implement the full-functional filter component,and unit tests

### PR DESCRIPTION
**Pull request by pierrelstan**
# Description
Following changes have been implemented:
- Add tests for the filter component
- Add and update the date picker functionalities:
  - The filters are closed when the cancel button is clicked.
   - Submit button failed when the start date is greater than the end date.
   - Submit is successful when the start date is less than the end Date.

Fixes (#340)

## Type of change

[comment]: # 'Please delete options that are not relevant.'

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Screenshots 
Screen Shot 2021-12-20 at 9 36 27 PM
Screen Shot 2021-12-20 at 9 36 48 PM

Screen Shot 2021-12-20 at 9 36 55 PM

Screen Shot 2021-12-20 at 9 37 18 PM

[comment]: # 'Please include screenshots of your changes if relevant.'

# How Has This Been Tested?

- [ ] Cypress integration
- [x] Cypress component tests
- [ ] Jest unit tests

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by pierrelstan** [comment]
1.
Screen Shot 2021-12-18 at 10 20 59 PM

2.
Screen Shot 2021-12-18 at 10 28 42 PM

**Review by VWRoli — CHANGES_REQUESTED** [review]
There are way too many state variables and conditions. Really hard to read the code. You don't need a variable for a true and a false condition. It's either true or false.  
In React for state variables, we use the useState() hook. If the variable name is `isError` the function name should be `setIsError`  and not `setError`. Follow the conventions.

You need a state variable to handle the error. One for handling the open state. And one for handling the submit state. 

'Filter is Open' and 'Filter is closed' is a little bit verbose in my opinion, should just turn the icon around. And also the style of the button. outlined should be closed and filled should be open. As I could figure out from the design.

`EDIT: I just noticed that it was already in the code and you did not write that part. My bad, sorry about that.`
As I said in your previous PR, Typography rarely needs classes. They are universal usually you just have to change the variant.
https://github.com/Greenstand/treetracker-web-map-client/blob/5b0f8c0971dd7bae98f2d85b581d3957fa27db2d/src/components/common/Filter.js#L194
Should be: `<Typography variant="h6" sx={{ letterSpacing: '0.04em' }}>`

___

https://github.com/Greenstand/treetracker-web-map-client/blob/5b0f8c0971dd7bae98f2d85b581d3957fa27db2d/src/components/common/Filter.js#L172
This should contain the text 'Featured Trees' and should be removed from the top.js file.
`<Typography variant="h3">Featured Trees</Typography>`

___

moment is installed for the project use that to format the date: 
`const formatDates = (date) => {
    return moment(date, 'ddd MMM DD YYYY HH:mm:ss').format('MM-DD-YYYY');
  };`

___

https://github.com/Greenstand/treetracker-web-map-client/blob/5b0f8c0971dd7bae98f2d85b581d3957fa27db2d/src/components/common/Filter.js#L203
This line creates warnings in the code.  Remove it.

___

You left a couple of classes in the code that is unused, remove this also.

At the bottom, I attached my solution for reference, just so you can see that we don't need so many variables. Only I could not figure out the disable button logic yet. 

___

`
import FilterListRoundedIcon from '@mui/icons-material/FilterListRounded';
import AdapterDateFns from '@mui/lab/AdapterDateFns';
import DesktopDatePicker from '@mui/lab/DesktopDatePicker';
import LocalizationProvider from '@mui/lab/LocalizationProvider';
import Box from '@mui/material/Box';
import Button from '@mui/material/Button';
import Grid from '@mui/material/Grid';
import TextField from '@mui/material/TextField';
import Typography from '@mui/material/Typography';
import log from 'loglevel';
import { makeStyles } from 'models/makeStyles';
import moment from 'moment';
import React from 'react';

const useStyles = makeStyles()((theme) => ({
  title: {
    display: 'flex',
    justifyContent: 'space-between',
  },
  filterButtonText: {
    textTransform: 'none',
    marginLeft: '8px',
  },
  filterIcon: {
    transform: 'rotate(180deg)',
  },
  container: {
    marginTop: theme.spacing(12),
  },
  inputLabel: {
    color: theme.palette.textPrimary.main,
    fontFamily: 'Lato',
    letterSpacing: '0.5px',
  },
  spaceBetween: {
    marginRight: theme.spacing(5),
  },
  spaceBelow: {
    marginBottom: theme.spacing(5),
  },

  dateFieldContainer: {
    marginTop: theme.spacing(5),
  },
  dateField: {
    borderBottom: 'none !important',
    border: '1px solid #C4C4C4',
    borderRadius: '4px',
  },
}));

function Filter(props) {
  const { onFilter } = props;
  const { classes } = useStyles();
  const [startDate, setStartDate] = React.useState('');
  const [endDate, setEndDate] = React.useState('');
  const [isError, setIsError] = React.useState(false);
  const [isFilterOpen, setIsFilterOpen] = React.useState(true);
  const [onSubmit, setOnSubmit] = React.useState(false);

  const formatDates = (date) => {
    return moment(date, 'ddd MMM DD YYYY HH:mm:ss').format('MM-DD-YYYY');
  };

  const handleCancel = () => {
    setOnSubmit(false);
    setStartDate('');
    setEndDate('');
    setIsFilterOpen(false);
    setIsError(false);
  };

  const handleSubmit = () => {
    log.log('submit');
    if (startDate > endDate) {
      setIsError(true);
    } else {
      setOnSubmit(true);
      onFilter({ startDate, endDate });
      setIsFilterOpen(!isFilterOpen);
      setIsError(false);
    }
  };

  return (
    <Box sx={{ width: 1 }}>
      <form onSubmit={handleSubmit}>
        <Box className={classes.title}>
          <Typography variant="h3" sx={{ color: 'textPrimary.main' }}>
            Featured Trees
          </Typography>
          <Button
            variant={isFilterOpen ? 'contained' : 'outlined'}
            color="primary"
            onClick={() => setIsFilterOpen(!isFilterOpen)}
            sx={{ color: !isFilterOpen ? 'textPrimary.main' : '' }}
          >
            <FilterListRoundedIcon
              fontSize="small"
              className={isFilterOpen ? classes.filterIcon : null}
            />
            <Typography className={classes.filterButtonText}>
              Filters{' '}
              {onSubmit &&
                `(${formatDates(startDate)} - ${formatDates(endDate)})`}
            </Typography>
          </Button>
        </Box>
        {isFilterOpen && (
          <Box className={classes.container} data-cy="hidden">
            <Grid container>
              <Grid item xs={12}>
                <Typography
                  variant="h6"
                  sx={{ letterSpacing: '0.04em', color: 'textPrimary.main' }}
                >
                  Planted between (timeline)
                </Typography>
              </Grid>
              <LocalizationProvider dateAdapter={AdapterDateFns}>
                <Grid item container sx={{ mt: 5 }} columnSpacing={{ xs: 2 }}>
                  <Grid item sm={6}>
                    <DesktopDatePicker
                      label="Start Date"
                      className={` ${classes.spaceBetween} ${classes.spaceBelow}`}
                      value={startDate}
                      onChange={(newValue) => {
                        setStartDate(newValue);
                      }}
                      renderInput={(params) => (
                        <TextField
                          {...params}
                          label="Start Date"
                          variant="outlined"
                          size="small"
                          error={isError}
                          className={` ${classes.spaceBetween} ${classes.spaceBelow}`}
                          color="secondary"
                          InputLabelProps={{
                            shrink: true,
                            className: classes.inputLabel,
                          }}
                          sx={{ width: 1 }}
                        />
                      )}
                    />
                  </Grid>
                  <Grid item xs={6}>
                    <DesktopDatePicker
                      label="End Date"
                      value={endDate}
                      onChange={(newValue) => {
                        setEndDate(newValue);
                      }}
                      renderInput={(params) => (
                        <TextField
                          {...params}
                          variant="outlined"
                          size="small"
                          error={isError}
                          className={` ${classes.spaceBetween} ${classes.spaceBelow}`}
                          color="secondary"
                          InputLabelProps={{
                            shrink: true,
                            className: classes.inputLabel,
                          }}
                          sx={{ width: 1 }}
                        />
                      )}
                    />
                  </Grid>
                </Grid>
              </LocalizationProvider>
            </Grid>
            <Box sx={{ gap: 2, display: 'flex', justifyContent: 'end' }}>
              <Button variant="text" onClick={() => handleCancel()}>
                Cancel
              </Button>
              <Button
                onClick={handleSubmit}
                color="primary"
                variant="contained"
              >
                Submit
              </Button>
            </Box>
          </Box>
        )}
      </form>
    </Box>
  );
}

export default Filter;

`

**Comment by pierrelstan** [comment]
@VWRoli Thank you for the review and explanations. I  made the recommended changes.

**Review by VWRoli — CHANGES_REQUESTED** [review]
https://github.com/Greenstand/treetracker-web-map-client/blob/24300de153476ab57ac5e76b29a45e09726b28fc/src/components/common/Filter.js#L36-L41
formatDates already does that. There is no reason to create another function to use `/` instead of `-`.

https://github.com/Greenstand/treetracker-web-map-client/blob/24300de153476ab57ac5e76b29a45e09726b28fc/src/components/common/Filter.js#L43-L45
Good one!

___

https://github.com/Greenstand/treetracker-web-map-client/blob/24300de153476ab57ac5e76b29a45e09726b28fc/src/components/common/Filter.js#L102-L110
If you open the theme.js you can find our default theme. There you can see that `variant="h3"`  by default has a good font-family, font-weight, and font size. Remove these and leave only the color, please.

https://github.com/Greenstand/treetracker-web-map-client/blob/24300de153476ab57ac5e76b29a45e09726b28fc/src/components/common/Filter.js#L121-L129
Same here.

___

When you apply a filter and open the filter component again, I don't think it should be deleted. As a user, I would like to edit the filter.

___

There is an error in the console. To get rid of it you have to add `mask="____-__-__"` line to the datepicker component.

Otherwise seems to be working, good job!

**Comment by VWRoli** [comment]
Great job @pierrelstan! One more thing could you align the "Featured Trees" title and the "Filter". Give the container box an `alignItems: 'center'`.

**Comment by pierrelstan** [comment]
> Great job @pierrelstan! One more thing could you align the "Featured Trees" title and the "Filter". Give the container box an `alignItems: 'center'`.

Thank you @VWRoli   Do you have any tips on how to create  Pixel-Perfect Layouts?

**Review by VWRoli — APPROVED** [review]

**Comment by dadiorchen** [comment]
@pierrelstan CSS is a language, https://developer.mozilla.org/en-US/docs/Web/CSS it's fine we can not do it perfectly now, and also `flex` is a important tech nowadays I think.

**Comment by pierrelstan** [comment]
@dadiorchen Thank you for mentioning CSS and flex.
I think,
I miss-formulating my question.

I wanted to know if they are any techniques to make my  code  pixel perfect 
for example: To make the website look exactly like the design.

**Comment by dadiorchen** [comment]
You mean using some tech to automatically generate the code? I don't know...

**Comment by pierrelstan** [comment]
> You mean using some tech to automatically generate the code? I don't know...

No. Some tech that can compare the design and the coded page for we can verify if the coded page is pixel-perfect .

**Comment by VWRoli** [comment]
I don't think that's necessary. It doesn't have to be pixel perfect, it probably can't be. We have to account for different devices and screen sizes. I think it's enough if you compare your work and the Figma design. You can tell if it looks the same or not.

**Comment by pierrelstan** [comment]
I get it now, @dadiorchen @VWRoli  thank you.

**Pull request merged**
