### PR TITLE
feat/theme playground

### PR DESCRIPTION
**Pull request by RubenSmn**
# Description
Add theme customization playground

Implements #431

## Type of change

[comment]: # 'Please delete options that are not relevant.'

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

- [ ] Cypress integration
- [ ] Cypress component tests
- [ ] Jest unit tests

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by RubenSmn** [comment]
### Current state
- can customize colors, updates the values across the editor
- color thumbnail to quickly see the colors
- can reset *whole* theme to default
- can enable auto reload, reloads when value changes

### Screenshot 
#### Full
image

#### Editor
image

**Comment by dadiorchen** [comment]
@RubenSmn this is awesome, are you implementing the component by yourself or you are using the existing solution?

**Comment by RubenSmn** [comment]
I'm building the components myself and using the https://bareynol.github.io/mui-theme-creator/ as a design reference/example.

**Comment by RubenSmn** [comment]
### Current state
- can customize typography
- can directly see changes in thumbnail
- prop rules to validate user input

### Screenshot
image

**Comment by RubenSmn** [comment]
Editing props works both ways! You can edit the from `InputFields` or from the textarea with all the styles.

**Comment by RubenSmn** [comment]
### Updated state:
- theme editor will use current custom theme if present
- theme editor will start in current theme mode
- fixed spacing not being passed to custom theme

*no  UI updates*

**Comment by dadiorchen** [comment]
@RubenSmn Just share some my experience, the font family relys on two factor: the font installed locally on the user's computer, manually dynamically load the font from web site via some meta indicator, like <link> so if we don't have font supported by these two approaches, then the font dont's work for current user/browser.

Basically we can manually load various fonts from fronts.google.com. 
Also, the font-weight matters, usually we just load the weight of that font we need, to save network traffic. 

And, there are some weird things I still don't figure out, is that even we download the same font and weight from the internet, I found sometimes they have minor difference with the Figma design, I don't know the reason, just a head up for you in case you run into some problem.

**Comment by RubenSmn** [comment]
@dadiorchen just implemented the basic font customization.
Now looking to store the used fonts in the local storage `themeObject`. The stored fonts should also be loaded when the theme is loaded from local storage. When that is working I will be looking at optimizing getting the fonts with just the required font-weights.

**Comment by dadiorchen** [comment]
@RubenSmn here are some relevant code:

https://github.com/Greenstand/treetracker-web-map-client/blob/75528cba577fca517aed4e25ec4643d13db7d443/src/pages/_document.js#L6-L24

**Comment by RubenSmn** [comment]
@dadiorchen I'm currently loading the fonts with the WebFontLoader [here](https://github.com/Greenstand/treetracker-web-map-client/pull/654/commits/2b2dfb6ecc27d38f2ef66e041317ae15fc4b43ec#diff-5bfabd7c7bac1d5b79ed9847492aecdaa2a72985eb1fb47536e9b76e67fcd9b6R130-R154)

**Comment by dadiorchen** [comment]
@RubenSmn that looks great

**Comment by RubenSmn** [comment]
### Updated state:
- localStorage stored theme has only one theme, using dark/light versions only on props that require them. (palette/components)
- custom fonts are optimized for the web app by adding only the used fonts

*no UI updates*

**Comment by RubenSmn** [comment]
### Updated state
-  every playground component has a test

*no UI updates*

**Comment by dadiorchen** [comment]
> ### Updated state
> * every playground component has a test
> 
> _no UI updates_

@RubenSmn I recommend the Test Driven Development, in this way, you build tests first, then the code, I rely on this heavily, and Cypress also brings great convenience to practice TDD, comparing to the FB recommended lib testing-library, because you can code watching the UI.
BTW, I think the principle for web map client in terms of the test coverage is no need for 100% unit test covering every component, if they already are covered by the integration test.

**Comment by RubenSmn** [comment]
@dadiorchen thanks for sharing your knowledge! I will try to apply this in the future, now that I know a little more about cypress!

**Pull request merged**
