### PR TITLE
Added Link to navbar Logo

### LINKED ISSUE #248: Add home page link for the logo icon.
By clicking the link on the logo icon, we can go back to the home page `/` anywhere. 
Screen Shot 2021-11-02 at 6 18 35 PM

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.

### PR DESCRIPTION
**Pull request by akash5100**
# Added Link to Navbar logo
* added '/' as a href to the navbar logo
* closes #248

### CODE REVIEW

**Comment by jwgatt** [comment]
What is the changed code in the package-lock.json file?

**Comment by dadiorchen** [comment]
@akash5100 I received your messagen in the slack, so you made it?

**Comment by akash5100** [comment]
> What is the changed code in the package-lock.json file?
All i did was npm i before running in localhost, do I need to restore this before making pull request?

**Comment by akash5100** [comment]
> @akash5100 I received your messagen in the slack, so you made it?

Is this correct? Do I need to restore json file,
I only installed the required packages with npm i to run it in localhost as mentioned in readme

**Comment by dadiorchen** [comment]
I think it's fine that the package-lock.json changed. Do you make it to jump to home by click the logo?

**Comment by dadiorchen** [comment]
@akash5100 why you close your PR, if you want to make some change, there is no need to close you PR, just simple commit new code against the branch you were working on , and push it again, then we can see the new progress in this PR page.

**Comment by akash5100** [comment]
I closed because I changed the package-lock.json file by mistake

**Comment by akash5100** [comment]
@dadiorchen I opened a new PR after closing this.

**Pull request closed without merging**
