### PR TITLE
feat(treeid): added MUIv5 skeleton loader component for tree info panel

### LINKED ISSUE #1039: Display progress block when loading new page
As the video showing, it is a bit confusing for user when we click next tree,  the old id and picture is still there and replaced by new ones when loaded, we should remove old content and replace with loading block (like this https://mui.com/material-ui/react-skeleton/#main-content) and display new content when ready.

https://dadior.s3.ap-northeast-1.amazonaws.com/Screen%20Recording%202022-09-30%20at%205.51.34%20PM.mp4?

Note, this issue is related to #976

### PR DESCRIPTION
**Pull request by andrewsu31098**
Created new component that uses MUIv5 Skeletons to display during [tree.id] transitions.
Also added custom react hook to detect when page is loading.

# Description

[comment]: # 'Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.'

Fixes #1039

## Type of change
- [x] New feature (non-breaking change which adds functionality)

## Screenshots

[comment]: # 'Please include screenshots of your changes if relevant.'

**Before** 
before

  **After** 
after

# Checklist:

- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by andrewsu31098** [comment]
I know the issue is closed but I'll post the PR incase you ever need it

**Comment by andrewsu31098** [comment]
I know the issue is closed but I'll post the PR incase you ever need it 
@dadiorchen

**Comment by dadiorchen** [comment]
@andrewsu31098 oh, this is a beautiful one for me, I totally approve of this one, @RubenSmn take a look, we did it before, but I'm afraid of adapting it because of the invasive manner, your solution hasn't that problem, and reusable!

**Review by RubenSmn — APPROVED** [review]
Amazing job! Great new hook that we might use in some other places!

**Comment by dadiorchen** [comment]
@andrewsu31098 if you want to join our community on slack, please send me your email address

**Comment by andrewsu31098** [comment]
Thank you guys. Also @dadiorchen i'm on the slack already

**Pull request merged**
