### PR TITLE
feat: handle no data detail pages

### LINKED ISSUE #737: The 404 page for cases that we can not find data for entities
We need to handle this case:

http://localhost:3000/planters/942

There isn't planter no.942, so we need to jump to 404 page (we have one /pages/404.js)

### PR DESCRIPTION
**Pull request by RubenSmn**
# Description
Handle no data planter page

Fixes  #737

## Type of change

[comment]: # 'Please delete options that are not relevant.'

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by RubenSmn** [comment]
@dadiorchen is this the direction you want to go with this?

**Comment by dadiorchen** [comment]
:D I don't know, what does that mean by returning `not-found`?

**Comment by RubenSmn** [comment]
I followed the documentation here: https://nextjs.org/docs/api-reference/data-fetching/get-server-side-props#notfound

**Comment by dadiorchen** [comment]
@RubenSmn I didn't know that, great, that definitely the way to go

**Comment by RubenSmn** [comment]
@dadiorchen do we also need to do this error handling for `trees` and `organizations` pages?

**Comment by dadiorchen** [comment]
@RubenSmn yes, I think we need to

**Comment by dadiorchen** [comment]
@RubenSmn thank you!

**Pull request merged**
