### PR TITLE
feat: add new zoom-in-out button on mobile

### LINKED ISSUE #598: Zoom in/out button on the mobile.
image

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

### PR DESCRIPTION
**Pull request by jeremydthomas**
# Description

[comment]: # 'Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.'

Fixes #598 

## Type of change

[comment]: # 'Please delete options that are not relevant.'

- [x ] New feature (non-breaking change which adds functionality)

## Screenshots

image

# How Has This Been Tested?

no cy test files available

# Checklist:

- [ x] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] My changes generate no new warnings
- [x ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by dadiorchen** [comment]
@jeremydthomas thanks for the contribution, I have a question, what if the draw is open, will the drawer hide the button?

**Comment by jeremydthomas** [comment]
> @jeremydthomas thanks for the contribution, I have a question, what if the draw is open, will the drawer hide the button?

I didn't think of that, I'll go check it here when I have some time @dadiorchen

**Comment by jeremydthomas** [comment]
I lowered the zindex value for the buttons so its below the drawers. Thanks for the reminder @dadiorchen, you are the best.

Heres a video I recorded for demonstration,

https://user-images.githubusercontent.com/63400531/170987581-0ab515c0-249c-418a-b804-6a7bac399652.mp4

**Comment by dadiorchen** [comment]
@jeremydthomas thank you! for you great job!

**Pull request merged**
