### PR TITLE
feat/tree info dialog

### LINKED ISSUE #555: New tree info details component
When click on the tree page's expand button, display this component. 
image

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

### PR DESCRIPTION
**Pull request by RubenSmn**
# Description
New `TreeInfoDialog` which requires a `tree` and `planter` data object. With optional `organization` data object.
Tests for rendering component with and without `organization`.

NOTE: Like and Share button have no functionality.

[comment]: # 'Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.'

Fixes #555 

## Type of change

[comment]: # 'Please delete options that are not relevant.'

- [x] New feature (non-breaking change which adds functionality)

## Screenshots
Desktop|Mobile
:-:|:-:
image|image

[comment]: # 'Please include screenshots of your changes if relevant.'

# How Has This Been Tested?

- [ ] Cypress integration
- [x] Cypress component tests
- [ ] Jest unit tests

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by dadiorchen** [comment]
@RubenSmn thank you for this huge contribution, I have some suggestions on this:
could you do a round of refining in terms of the details of styles/layout? I found it's not so accurate comparing to the figma design, please make the UI as possible as close to the design, including with/height/ border radius /font-size/ spacing. 
Here is some thing I found not respecting the design:
1. The main picture border radius is too big.
2. The dialog is 100% width of the screen in design, and bigger rounded corners. 
3. The share button: icon is different with design, (please export it from figma) shouldn't capitalize the text, shouldn't having shadow.
4. I feel the font size/family for planter/orgs is different with design.

I know this is strict for implementing a UI, but we need to be almost 100% align with the design, or we cann't get a beautiful app.

I saw you are using components from materialui, like dialog, grid, list, sometimes I feel inconvenient to control some details with them, and using raw element is easier for me, just a sharing of my experience.

**Comment by dadiorchen** [comment]
CSS is a dedicated job position in some companies, it's not so easy, I'm learning the sills too :)

**Comment by RubenSmn** [comment]
@dadiorchen updated the UI to better match the design with the help of your feedback. Extracted some components to make implementation of dynamic data more accessible. Also improved the responsiveness of the `captures`.

Added extra images for demonstration

image

**Comment by dadiorchen** [comment]
@RubenSmn good! Thank you for your amazing work!

**Pull request merged**
