### PR TITLE
feat: added tooltip to display planters/orgs name

### LINKED ISSUE #613: A tooltip to display the planter/org 's name.
When the mouse hovering on the planter or organizations box, show a tooltip to display the name of the entity.

image

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

### PR DESCRIPTION
**Pull request by Mohmn**
# Description

[comment]: # 'Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.'

Fixes #613

## Type of change

[comment]: # 'Please delete options that are not relevant.'

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Screenshots
Screenshot from 2022-06-16 01-17-54

[comment]: # 'Please include screenshots of your changes if relevant.'

# How Has This Been Tested?

- [ ] Cypress integration
- [ ] Cypress component tests
- [ ] Jest unit tests

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x]
Screenshot from 2022-06-16 01-17-45
 My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by dadiorchen** [comment]
That's nice, did you test the appearance on light mode? is it okay? in terms of the background, font color? @Mohmn

**Comment by Mohmn** [comment]
@dadiorchen updated the tool tip appearance based on theme
Screenshot from 2022-06-18 00-33-12
Screenshot from 2022-06-18 00-33-04

**Comment by dadiorchen** [comment]
That's nice!

**Comment by dadiorchen** [comment]
Thanks

**Comment by Mohmn** [comment]
Most Welcome

**Pull request merged**
