### PR TITLE
fix: tree badges are now dynamic

### LINKED ISSUE #714: Add badges component on the tree page
http://localhost:3000/trees/186735

Please implement these `badges` on the tree page, currently, there are `badges` on the panel, but it's hard-code.

`Verified trees` if `approved` property is true.
`Waiting for verify` opposite to the above.

`Token issued` if `token` is not null
`Token not issued` opposite to the above.

Image

### PR DESCRIPTION
**Pull request by nikhilpandeynp0505**
# Description

Fixes #714 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Screenshots

Screenshot 2022-08-01 at 3 52 07 PM

# How Has This Been Tested?

- [ ] Cypress integration
- [x] Cypress component tests
- [ ] Jest unit tests

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by dadiorchen** [comment]
@Mohmn could you help review this PR

**Review by Mohmn — APPROVED** [review]
looks good to me

**Comment by dadiorchen** [comment]
@nikhilpandeynp0505 I have some suggestion:
1. I think we missed a feature: the badge has two modes: enable/disable, so when the verified=false, the badge should be diabled, means the color is in gray, and we need to use the theme's palette to set the color. 
https://github.com/Greenstand/treetracker-web-map-client/blob/20722936e9d41d0da1a961856d3f0acc612e537f/src/context/themeContext.js#L167-L199

2. Please put the component (Badge) file to the components folder, so we can reuse it in the future, and also, I suggest you implement the Bedget.cy.js to mount the component and check the two modes in the unit/component test, I recommend this tool, it is a great way to build component, especially when the app grows huge.

**Comment by nikhilpandeynp0505** [comment]
Thanks for reviewing the pull request @dadiorchen and @Mohmn 

@dadiorchen I am new to the cypress tests and every time I am trying to run them it runs integration tests only. Can you please suggest how to run individual component tests using cypress commands?

**Comment by dadiorchen** [comment]
Did you try npm run cyu

Dadior Chen

在 2022年8月3日，15:09，nikhilpandeynp0505 ***@***.***> 写道：

﻿

Thanks for reviewing the pull request @dadiorchen<https://github.com/dadiorchen> and @Mohmn<https://github.com/Mohmn>

@dadiorchen<https://github.com/dadiorchen> I am new to the cypress tests and every time I am trying to run them it runs integration tests only. Can you please suggest how to run individual component tests using cypress commands?

**Comment by nikhilpandeynp0505** [comment]
@dadiorchen Thanks a lot! I have updated the PR. Please review.

**Comment by dadiorchen** [comment]
@nikhilpandeynp0505 thank your for you contribution!

**Pull request merged**
