### PR TITLE
fix: card shadow not equal to design

### LINKED ISSUE #575: Refine the shadow of these component
These box's shadow is more smoothy then our implementation, please refine it, you can find it here: http://localhost:3000/top

Please make sure the shadow works well on the dark mode (by clicking `theme` button on top right corner)

image

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

### PR DESCRIPTION
**Pull request by RubenSmn**
# Description
Fixes #575 
Dark needs a *harder* shadow due to the fact that card will fade in with the background.

## Type of change

[comment]: # 'Please delete options that are not relevant.'

- [x] Bug fix (non-breaking change which fixes an issue)

## Screenshots

Light|Dark
:-:|:-:
image|image

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by RubenSmn** [comment]
Maybe for the Featured Planters this is not needed as the card has a totally different color than the background.

**Comment by dadiorchen** [comment]
Nice! 
I think the shadow for the planter is fine, the shadow is telling the user the logic of this UX/UI

**Comment by RubenSmn** [comment]
@dadiorchen does this need any improvement?

**Comment by dadiorchen** [comment]
Sorry for the delay, I was planning to download your PR and check the result on my computer, will back to you later.

**Comment by dadiorchen** [comment]
Let's close this PR and consider a more general solution based on `elevation` in the future. Also this design is kind of random, just one single case of special shadow rather than a consistent style crossing the whole app.

**Pull request closed without merging**
