### PR TITLE
feat: uniform imports 

### LINKED ISSUE #1313: Import aliases not followed throughout the codebase
---
 Problem: Import aliases not followed throughout the codebase #1313
 
image

### PR DESCRIPTION
**Pull request by khalatevarun**
# Description

[comment]: # 'Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.'

Fixes #1313

* Fixes uniform import of import alias throughout the project.
* Used a codemod to fix this issue - can refer to the following [link](https://astexplorer.net/#/gist/b6536a69025e1503a8004aa350549590/8af3160f868becdd02870ccb408efb89a4c15a60) 

## Type of change

[comment]: # 'Please delete options that are not relevant.'

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Screenshots

[comment]: # 'Please include screenshots of your changes if relevant.'

|       Before        |       After        |
| :-----------------: | :----------------: |
| "screenshot before" | "screenshot after" |

# How Has This Been Tested?

- [ ] Cypress integration
- [ ] Cypress component tests
- [ ] Jest unit tests

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by RubenSmn** [comment]
@khalatevarun did you have a script for this or did you do it by hand?

**Comment by khalatevarun** [comment]
I wrote a script @RubenSmn 
you can check it out here 
https://astexplorer.net/#/gist/b6536a69025e1503a8004aa350549590/8af3160f868becdd02870ccb408efb89a4c15a60

**Comment by RubenSmn** [comment]
Maybe we can run this by default with the `lintstaged` scripts @dadiorchen what do you think?

**Comment by RubenSmn** [comment]
@khalatevarun could you resolve the merge conflict?

**Comment by khalatevarun** [comment]
yes will do

**Comment by khalatevarun** [comment]
have resolved conflicts @RubenSmn

**Comment by dadiorchen** [comment]
Guys, is it okay now to merge this PR?

**Comment by RubenSmn** [comment]
@khalatevarun I'm sorry I merged another PR and now there are conflicts again.

Do you think you could add your script to a new `scripts` directory and run it with `commitlint`. I think if we don't do that we are still going to get the `../../` when importing new files.

**Comment by khalatevarun** [comment]
@RubenSmn i have resolved the conflicts but not able to revert change log changes, could you please help me with it and revert the changelog changes?

**Comment by RubenSmn** [comment]
@khalatevarun I don't see any issue with the current status of the files, looks to me like everything is just fine.

**Comment by khalatevarun** [comment]
> @khalatevarun I don't see any issue with the current status of the files, looks to me like everything is just fine.
> 
> I did restart the test since there was some network error.

okay

**Comment by khalatevarun** [comment]
@RubenSmn @dadiorchen  happy to share that I could successfully add the script with the `lintstaged` scripts. It works as expected!

**Comment by khalatevarun** [comment]
Can we merge this? @dadiorchen @RubenSmn

**Review by RubenSmn — CHANGES_REQUESTED** [review]
Could you move the `codeshift.js` to a new folder called `scripts` that way the project structure stays clean

**Comment by khalatevarun** [comment]
Updated, does this look good? @dadiorchen

**Comment by RubenSmn** [comment]
Yes @khalatevarun I'll test it locally in a bit

**Review by RubenSmn — APPROVED** [review]
Awesome work! This will improve the quality of our code :+1:

**Pull request merged**
