### PR TITLE
feat: modify FeaturedTreesSlider to support display of small sized im…

### LINKED ISSUE #308: FeaturedTreesSlider supports small size
We will reuse the slider on this page, with a property `size=small` so we can show a smaller one here:
https://www.figma.com/proto/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap?node-id=2497%3A11031&scaling=min-zoom&page-id=2497%3A9322&starting-point-node-id=2497%3A11031&show-proto-sidebar=1

Screen Shot 2021-11-26 at 4 07 55 PM

---

Some hints for building components:

- This kind of issue is about creating a new component, it might not need to mount it in the whole app, to know how to create a component separately, please check the tutorial below.
- Design resource: https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap?node-id=2497%3A11584
- A tutorial of how to use the Cypress component tool to build components:
  https://github.com/Greenstand/treetracker-wallet-web#how-to-build-a-component
- We are using MaterialUI to build the app: https://material-ui.com/
- Please mount the component with `import { mountWithTheme as mount } from '../../models/test-utils';` to get our theme imported.
- Please use MaterialUI `theme.spacing(x)` as possible as we can, so the component is more responsive
- When you are ready to raise PR for the component, please attach the screenshot of the component for review.
- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

### PR DESCRIPTION
**Pull request by pratikmdhr**
…ages

# Description

FeaturedTreesSlider can now take in size="small" props and display smaller sized images. If size is not passed in, the original (default) size of images will be displayed.

Fixes #308

## Type of change

[comment]: # 'Please delete options that are not relevant.'

- [x] New feature (non-breaking change which adds functionality)

## Screenshots 

[comment]: # 'Please include screenshots of your changes if relevant.'
`<FeaturedTreesSlider trees={trees} size="small"/>`
small

[Default]
`<FeaturedTreesSlider trees={trees}/>`
default

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by dadiorchen** [comment]
@pratikmdhr if you think the code is working, feel free to set it ready for merge

**Review by VWRoli — APPROVED** [review]
Great job @pratikmdhr!
Advice for the future though. For every issue you working on create a new branch. It's easier to go back if there is something wrong. Google some git branching best practices if you have some time.

**Comment by pratikmdhr** [comment]
> Great job @pratikmdhr! Advice for the future though. For every issue you working on create a new branch. It's easier to go back if there is something wrong. Google some git branching best practices if you have some time.

Thanks and yes you are right I should start creating a new branch from now on

**Review by QuaidBartolomei — APPROVED** [review]
Good job 👍

**Comment by dadiorchen** [comment]
Thank you all!

**Pull request merged**
