### PR TITLE
Fix quick swipe bug on mobile

### LINKED ISSUE #1149: Quick swipe right on slider closes the drawer on mobile
https://user-images.githubusercontent.com/53157755/198154858-ccee1463-7277-46b4-91db-eb8086b1e464.mp4

### PR DESCRIPTION
**Pull request by ojafero**
# Description

Fixes #1149 

## Type of change

[comment]: # 'Please delete options that are not relevant.'

- [x] Bug fix (non-breaking change which fixes an issue)

## Video
Before

https://user-images.githubusercontent.com/53157755/198156488-c87b8a1c-b6ed-4d79-9685-b8cf04eee39d.mp4

After:

https://user-images.githubusercontent.com/53157755/198155878-c4866273-da3e-4e63-bd4b-f8e5d7de8295.mp4

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by dadiorchen** [comment]
exellent job! because the drawer is pretty complicated now, I need hold on and take some time to review/try/test it.

**Comment by RubenSmn** [comment]
I justed tested this on Samsung Internet on a real device and it seems to work jist fine with the current version, where/when is this occuring?

**Comment by ojafero** [comment]
> I justed tested this on Samsung Internet on a real device and it seems to work just fine with the current version, where/when is this occuring?

@RubenSmn This bug also occurred on android for me. When you open the drawer and make a quick right swipe in the **first** container of cards, the drawer should close.

**Comment by RubenSmn** [comment]
@ojafero Okay last check I did was on a `wallets` page there it was working just fine. I just checked on the `top` page and it has the bug you describe. I think we should investigate what is causing this issue first instead of creating a fix.

**Comment by ojafero** [comment]
@RubenSmn On the wallets page, once you scroll down to the slider, scrollTop becomes greater than 0. This line runs in the code which prevents the drawer from closing. 
`if (contentRef.current.scrollTop > 0) {
      event.stopPropagation();
  }`

 If you don’t scroll down on the wallets page and make a quick right swipe, the bug remains.
 
 

https://user-images.githubusercontent.com/53157755/198396030-eef34a74-0666-4289-aaec-01ad6d99be47.mp4

**Comment by RubenSmn** [comment]
Awesome I see the issue now! Great catch!

**Comment by dadiorchen** [comment]
This is a great PR, but let's achieve the code there and wait the feedback from end user, if this become critical, we will back to here and merge the code, but for now, to keep the drawer simple, I will close this PR and keep monitoring this bug.

**Pull request closed without merging**
