### PR TITLE
chore: disable map bounds

### LINKED ISSUE #1469: Disable map bounds on admin dashboard
# Description

Disable the map bounds for the /admin pages. There is no need to display the bounds since we have inputs for them.

To reproduce
- visit: https://next-dev.treetracker.org/admin/global
- click on the map tab
- move the map

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- For design guidelines checkout our [Figma design](https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap).
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

### PR DESCRIPTION
**Pull request by muhon9**
# Description

# Disabled the map bounds for the /admin pages

Fixes #1469
## Type of change

[comment]: # 'Please delete options that are not relevant.'

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Screenshots

[comment]: # 'Please include screenshots of your changes if relevant.'

|       Before        |       After        |
| :-----------------: | :----------------: |
| "screenshot before" | "screenshot after" |

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by muhon9** [comment]
@RubenSmn please check the pull request. I am confused it disables bounds for every page. How can we make it only for /admin pages or is it ok

**Review by RubenSmn — COMMENTED** [review]
This disables the bounds everywhere and not only on the admin page. On the admin page we use `components/GlobalMapLayout`, maybe we can find a solution there?

**Comment by muhon9** [comment]
@RubenSmn I was thinking the same. Let me check if I can find the solution in other way

**Comment by muhon9** [comment]
@RubenSmn please check if it's ok. The only problem with it is that for every route change the useEffect witll run

**Review by RubenSmn — APPROVED** [review]
I think this is a good approach!

**Comment by muhon9** [comment]
@RubenSmn thanks. Let me know if we can approach any more optimized way.

**Comment by dadiorchen** [comment]
This is good, thank you!

**Pull request merged**
