### PR TITLE
Fix: dark theme bug

### LINKED ISSUE #1091: A bug for the dark theme
Sometimes the theme get messy, like below:

Image

To reproduce:
* Open the map
* Change to dark theme
* Close the map
* Open it in a new tab

### PR DESCRIPTION
**Pull request by ojafero**
# Description

The bug was due to mismatch between content rendered on server and client. I fixed the bug by accessing local storage on client side.

Fixes #1091 

## Type of change

- Bug fix (non-breaking change which fixes an issue)
## Video

https://user-images.githubusercontent.com/53157755/197304215-bbccc527-ad3c-491d-9ee9-9a1848022ae5.mp4

# Checklist:

- I have performed a self-review of my own code
- I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by dadiorchen** [comment]
@ojafero great job! thank you, if you want to join our community, please send me your email!

**Comment by RubenSmn** [comment]
This causing the initial value of `theme` to be undefined, see [this line](https://github.com/Greenstand/treetracker-web-map-client/blob/beta/src/context/themeContext.js#L335), this should not happen since the default value is always "light"

**Comment by dadiorchen** [comment]
@RubenSmn so what should we do now? that's the suggestion?

**Comment by RubenSmn** [comment]
@dadiorchen no worries, already fixed it with #1138

**Pull request merged**
