### PR TITLE
fix(playground): runtime error prop dark

### LINKED ISSUE #690: Bug: runtime error setPropByPath
### Description
When trying to set the `dark` prop on the `primary` color in the palette config.
There is a runtime error saying that the `dark` property is undefined

The same error on the `secondary` color

EDIT: Happens when editing the dark theme, when editing the light theme the `light` prop is undefined

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

### PR DESCRIPTION
**Pull request by RubenSmn**
# Description
Fixes the runtime error

[comment]: # 'Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.'

Fixes  #690

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by dadiorchen** [comment]
@RubenSmn can you analyze the failure of the unit test above? Seems the theme change related, but I wonder why just this component (tagChip) failed?

**Comment by dadiorchen** [comment]
When I run it locally, the TagChip.cy.js, the error:

```
Uncaught TypeError: Failed to execute 'removeEventListener' on 'EventTarget': 2 arguments required, but only 1 present.
    at eval (themeContext.js?a8d9:393:14)
    at HTMLUnknownElement.callCallback (react-dom.development.js?dd2c:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js?dd2c:3994:1)
    at invokeGuardedCallback (react-dom.development.js?dd2c:4056:1)
    at flushPassiveEffectsImpl (react-dom.development.js?dd2c:23543:1)
    at unstable_runWithPriority (scheduler.development.js?2fb7:468:1)
    at runWithPriority$1 (react-dom.development.js?dd2c:11276:1)
    at flushPassiveEffects (react-dom.development.js?dd2c:23447:1)
    at eval (react-dom.development.js?dd2c:23479:1)
```

**Comment by dadiorchen** [comment]
@RubenSmn I have solved this prolem, don't worry about this.

**Comment by RubenSmn** [comment]
@dadiorchen did it happen because of the `removeEventListener` not getting tbe name of the custom event?

**Comment by dadiorchen** [comment]
@RubenSmn yes, I added the custom event name you added, seems work now

**Pull request merged**
