### PR TITLE
Search box

### LINKED ISSUE #869: The web map UI, page/component for search box
Implement the Search Box, and the auto-completion list as below:

Please DO NOT add it into the app, instead, use unit cypress tool to test the feature.

Image

The UI design file is here: https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap?node-id=8797%3A34191

Refer to https://github.com/Greenstand/treetracker-search

### PR DESCRIPTION
**Pull request by Mohmn**
# Description

[comment]: # 'Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.'

Fixes #869

## Type of change

[comment]: # 'Please delete options that are not relevant.'

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Screenshots
Screenshot from 2022-09-04 15-05-30
Screenshot from 2022-09-04 15-05-16

[comment]: # 'Please include screenshots of your changes if relevant.'

# How Has This Been Tested?

- [ ] Cypress integration
- [x] Cypress component tests
- [ ] Jest unit tests

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by dadiorchen** [comment]
@kparikh9, @Mohmn is working on this search box feature, you two can establish some connection on the search feature, exchange ideas and so on.

**Comment by Mohmn** [comment]
@kparikh9 can u provide me a sample of json result im supposed to get from the search api

**Comment by Mohmn** [comment]
@dadiorchen search component is done from my side, can u review it

**Comment by kparikh9** [comment]
@Mohmn here are some documents that could be returned

```
{
        "db_table_id":116,
        "db_table_name":"tree_species",
        "name":"more",
        "desc":"test2",
        "active":false,
        "value_factor":0,
        "id":"f2c3b03e-24aa-4d8a-8209-248a8989b09c",
        "_version_":1743630536276967425
},
{
        "db_table_id":2,
        "db_table_name":"planter",
        "first_name":"vedran",
        "last_name":"tolic",
        "email":"vedrantolic89@gmail.com",
        "organization":"q alliance",
        "phone":"00385917889623",
        "pwd_reset_required":false,
        "id":"5ab5fc72-d911-458a-b241-96765798e6f9",
        "_version_":1743630553192595456
},
{
        "db_table_id":30,
        "db_table_name":"tag",
        "name":"test4",
        "active":true,
        "public":true,
        "id":"21e28a60-9373-4050-b1f5-5076baffffdf",
        "_version_":1743630563479126017
}
```

**Comment by dadiorchen** [comment]
@Mohmn super! thank you for the contribution!

**Pull request merged**
