### PR TITLE
feat: facebook like button

### LINKED ISSUE #310: The like component and function
We still don't have a login account on the website, so we are considering using the 3rd-party function for this, for example, the Facebook like, so this issue is about building the component and integrating the 3rd-party like button into our tree photo.

Screen Shot 2021-11-26 at 4 53 40 PM

---

Some hints for building components:

- This kind of issue is about creating a new component, it might not need to mount it in the whole app, to know how to create a component separately, please check the tutorial below.
- Design resource: https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap?node-id=2497%3A11584
- A tutorial of how to use the Cypress component tool to build components:
  https://github.com/Greenstand/treetracker-wallet-web#how-to-build-a-component
- We are using MaterialUI to build the app: https://material-ui.com/
- Please mount the component with `import { mountWithTheme as mount } from '../../models/test-utils';` to get our theme imported.
- Please use MaterialUI `theme.spacing(x)` as possible as we can, so the component is more responsive
- When you are ready to raise PR for the component, please attach the screenshot of the component for review.
- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

### PR DESCRIPTION
**Pull request by cavesdev**
# Description

Closes #310 

Added a Facebook like button to the tree details page. The like is linked to a specific URL (using the tree id) and users must have a FB account to like the tree.

## Type of change

[comment]: # 'Please delete options that are not relevant.'

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Screenshots 

Screen Shot 2022-01-03 at 12 40 25

# How Has This Been Tested?

- [ ] Cypress integration
- [ ] Cypress component tests
- [ ] Jest unit tests

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by VWRoli — CHANGES_REQUESTED** [review]
Not working on my side.
Screenshot from 2022-01-05 08-32-59
And you get this error message while rendering sometimes:
Screenshot from 2022-01-05 08-34-28

Tried it with different browsers like Brave, Chrome, and Firefox.

**Comment by dadiorchen** [comment]
Maybe we need to load some js file from FB?

**Comment by cavesdev** [comment]
> Maybe we need to load some js file from FB?

The Facebook's SDK is being loaded at the beginning.

One problem I faced: depending on your browser's configuration, it may be blocking requests to Facebook. For example, I use Edge with Strict Tracking Protection and it doesn't show the like button.
Screen Shot 2022-01-06 at 13 03 22

I updated the code to test if the SDK is loaded before attempting to use it.

**Review by VWRoli — CHANGES_REQUESTED** [review]
Seems like the error message is gone but still can't see it.

**Comment by cavesdev** [comment]
Is there anyone else that can test this? On my side it's working so I don't know what to fix :(

**Comment by dadiorchen** [comment]
@VWRoli can you help to test it and do some research on your side?

**Comment by VWRoli** [comment]
> @VWRoli can you help to test it and do some research on your side?

Sure, I will take a look at it.

**Comment by VWRoli** [comment]
@cavesdev can you tell me what OS and browser do you use? Can you show me a screenshot of the inspected element?

Screenshot from 2022-01-15 09-45-21

My best guess is that we run it locally with http, instead of https, and that causes the problem. Because we load the scripts, just the iframe does not have a height and width. If that is the problem then it should work when we run it on a public domain. Not sure though, it is just a theory.

**Comment by dadiorchen** [comment]
Is this useful? https://create-react-app.dev/docs/using-https-in-development/

**Comment by VWRoli** [comment]
> Is this useful? https://create-react-app.dev/docs/using-https-in-development/

Yes, it was. Set up HTTPS for next, but the like button still does not work. It seems I have to dig deeper.

**Comment by VWRoli** [comment]
Found the problem, staring right in my face. https://developers.facebook.com/docs/plugins/like-button
Screenshot from 2022-01-17 09-27-02

Switched my location to somewhere else and the like button worked. 
Screenshot from 2022-01-17 09-28-26

So it is just location and policy issues, the component itself is working fine.

**Comment by cavesdev** [comment]
Oh I see, sorry I'm just seeing your messages! Nice catch, will it be a problem for users on those regions? It will be awkward if some users see the button and some don't.

**Comment by dadiorchen** [comment]
oh.... funny problem... the whole Europe? it seems unacceptable...

**Comment by dadiorchen** [comment]
@cavesdev can you solve the conflict above and merge your code to branch, we can raise new issue for the problem mentioned above.

**Comment by cavesdev** [comment]
Done! Pulled the most recent changes from web-map-site

**Comment by dadiorchen** [comment]
Thanks!

**Pull request merged**
