### PR TITLE
feat(ui): add theme toggle button on embed pages

### LINKED ISSUE #791: Theme mode toggle on embed pages
### Description
Visiting: http://localhost:3000/trees/701767?embed=true
The user does not have an option to switch between `dark` and `light` themes.
We could use the already exisiting `ChangeThemeButton`

localhost_3000_trees_701767_embed=true

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

### PR DESCRIPTION
**Pull request by tranquanghuy0801**
# Description

Add theme toggle button on embed pages. This button is left to the search button.

Fixes #791 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Screenshots

Dark theme on embed pages

image

# How Has This Been Tested?

- [x] Jest unit tests

# Checklist:

- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by dadiorchen** [comment]
@tranquanghuy0801 we need to hold on this feature for a while and waiting the release of beta, this feature belongs to the version after beta

**Comment by dadiorchen** [comment]
Adding feature would delay the current version by testing, debugging, and so on

**Comment by tranquanghuy0801** [comment]
All good. thanks for letting me know

**Comment by dadiorchen** [comment]
We need re-design the UX now, let's close this PR first and then back to the feature if the design is done.

**Pull request closed without merging**
